// This file is auto-generated by build/build.ts. Do not edit directly.

export const brandsIcons = {
  "42-group": {
    "minVersion": "5.15.0"
  },
  "500px": {
    "minVersion": "4.4.0"
  },
  "accessible-icon": {
    "minVersion": "5.0.0"
  },
  "accusoft": {
    "minVersion": "5.0.0"
  },
  "adn": {
    "minVersion": "3.2.0"
  },
  "adversal": {
    "minVersion": "5.0.0"
  },
  "affiliatetheme": {
    "minVersion": "5.0.0"
  },
  "airbnb": {
    "minVersion": "5.8.0"
  },
  "algolia": {
    "minVersion": "5.0.0"
  },
  "alipay": {
    "minVersion": "5.3.0"
  },
  "amazon": {
    "minVersion": "4.4.0"
  },
  "amazon-pay": {
    "minVersion": "5.0.2"
  },
  "amilia": {
    "minVersion": "5.0.0"
  },
  "android": {
    "minVersion": "3.2.0"
  },
  "angellist": {
    "minVersion": "4.2.0"
  },
  "angrycreative": {
    "minVersion": "5.0.0"
  },
  "angular": {
    "minVersion": "5.0.0"
  },
  "app-store": {
    "minVersion": "5.0.0"
  },
  "app-store-ios": {
    "minVersion": "5.0.0"
  },
  "apper": {
    "minVersion": "5.0.0"
  },
  "apple": {
    "minVersion": "3.2.0"
  },
  "apple-pay": {
    "minVersion": "5.0.0"
  },
  "arch-linux": {
    "minVersion": "7.2.0"
  },
  "artstation": {
    "minVersion": "5.6.0"
  },
  "asymmetrik": {
    "minVersion": "5.0.0"
  },
  "atlassian": {
    "minVersion": "5.6.0"
  },
  "audible": {
    "minVersion": "5.0.0"
  },
  "autoprefixer": {
    "minVersion": "5.0.0"
  },
  "avianex": {
    "minVersion": "5.0.0"
  },
  "aviato": {
    "minVersion": "5.0.0"
  },
  "aws": {
    "minVersion": "5.0.0"
  },
  "bandcamp": {
    "minVersion": "4.7.0"
  },
  "battle-net": {
    "minVersion": "5.8.0"
  },
  "behance": {
    "minVersion": "4.1.0"
  },
  "bilibili": {
    "minVersion": "6.0.0-beta2"
  },
  "bimobject": {
    "minVersion": "5.0.0"
  },
  "bitbucket": {
    "minVersion": "3.2.0"
  },
  "bitcoin": {
    "minVersion": "5.0.0"
  },
  "bity": {
    "minVersion": "5.0.0"
  },
  "black-tie": {
    "minVersion": "4.4.0"
  },
  "blackberry": {
    "minVersion": "5.0.0"
  },
  "blogger": {
    "minVersion": "5.0.0"
  },
  "blogger-b": {
    "minVersion": "5.0.0"
  },
  "bluesky": {
    "minVersion": "6.5.2"
  },
  "bluetooth": {
    "minVersion": "4.5.0"
  },
  "bluetooth-b": {
    "minVersion": "4.5.0"
  },
  "board-game-geek": {
    "minVersion": "7.2.0"
  },
  "bootstrap": {
    "minVersion": "5.8.0"
  },
  "bots": {
    "minVersion": "6.0.0-beta1"
  },
  "brave": {
    "minVersion": "6.5.0"
  },
  "brave-reverse": {
    "minVersion": "6.5.0"
  },
  "btc": {
    "minVersion": "3.2.0"
  },
  "buffer": {
    "minVersion": "5.8.0"
  },
  "buromobelexperte": {
    "minVersion": "5.0.0"
  },
  "buy-n-large": {
    "minVersion": "5.11.0"
  },
  "buysellads": {
    "minVersion": "4.3.0"
  },
  "canadian-maple-leaf": {
    "minVersion": "5.6.0"
  },
  "cash-app": {
    "minVersion": "7.0.0"
  },
  "cc-amazon-pay": {
    "minVersion": "5.0.2"
  },
  "cc-amex": {
    "minVersion": "4.2.0"
  },
  "cc-apple-pay": {
    "minVersion": "5.0.0"
  },
  "cc-diners-club": {
    "minVersion": "4.4.0"
  },
  "cc-discover": {
    "minVersion": "4.2.0"
  },
  "cc-jcb": {
    "minVersion": "4.4.0"
  },
  "cc-mastercard": {
    "minVersion": "4.2.0"
  },
  "cc-paypal": {
    "minVersion": "4.2.0"
  },
  "cc-stripe": {
    "minVersion": "4.2.0"
  },
  "cc-visa": {
    "minVersion": "4.2.0"
  },
  "centercode": {
    "minVersion": "5.0.0"
  },
  "centos": {
    "minVersion": "5.6.0"
  },
  "chrome": {
    "minVersion": "4.4.0"
  },
  "chromecast": {
    "minVersion": "5.8.0"
  },
  "circle-zulip": {
    "minVersion": "7.2.0"
  },
  "claude": {
    "minVersion": "7.2.0"
  },
  "cloudflare": {
    "minVersion": "5.15.0"
  },
  "cloudscale": {
    "minVersion": "5.0.0"
  },
  "cloudsmith": {
    "minVersion": "5.0.0"
  },
  "cloudversify": {
    "minVersion": "5.0.0"
  },
  "cmplid": {
    "minVersion": "6.0.0-beta1"
  },
  "codepen": {
    "minVersion": "4.1.0"
  },
  "codiepie": {
    "minVersion": "4.5.0"
  },
  "confluence": {
    "minVersion": "5.6.0"
  },
  "connectdevelop": {
    "minVersion": "4.3.0"
  },
  "contao": {
    "minVersion": "4.4.0"
  },
  "cotton-bureau": {
    "minVersion": "5.10.0"
  },
  "cpanel": {
    "minVersion": "5.0.0"
  },
  "creative-commons": {
    "minVersion": "4.4.0"
  },
  "creative-commons-by": {
    "minVersion": "5.0.11"
  },
  "creative-commons-nc": {
    "minVersion": "5.0.11"
  },
  "creative-commons-nc-eu": {
    "minVersion": "5.0.11"
  },
  "creative-commons-nc-jp": {
    "minVersion": "5.0.11"
  },
  "creative-commons-nd": {
    "minVersion": "5.0.11"
  },
  "creative-commons-pd": {
    "minVersion": "5.0.11"
  },
  "creative-commons-pd-alt": {
    "minVersion": "5.0.11"
  },
  "creative-commons-remix": {
    "minVersion": "5.0.11"
  },
  "creative-commons-sa": {
    "minVersion": "5.0.11"
  },
  "creative-commons-sampling": {
    "minVersion": "5.0.11"
  },
  "creative-commons-sampling-plus": {
    "minVersion": "5.0.11"
  },
  "creative-commons-share": {
    "minVersion": "5.0.11"
  },
  "creative-commons-zero": {
    "minVersion": "5.0.11"
  },
  "critical-role": {
    "minVersion": "5.4.0"
  },
  "css": {
    "minVersion": "6.7.0"
  },
  "css3": {
    "minVersion": "3.1.0"
  },
  "css3-alt": {
    "minVersion": "5.0.0"
  },
  "cuttlefish": {
    "minVersion": "5.0.0"
  },
  "d-and-d": {
    "minVersion": "5.0.0"
  },
  "d-and-d-beyond": {
    "minVersion": "5.4.0"
  },
  "dailymotion": {
    "minVersion": "5.12.1"
  },
  "dart-lang": {
    "minVersion": "6.6.0"
  },
  "dashcube": {
    "minVersion": "4.3.0"
  },
  "debian": {
    "minVersion": "6.4.1"
  },
  "deezer": {
    "minVersion": "5.13.1"
  },
  "delicious": {
    "minVersion": "4.1.0"
  },
  "deploydog": {
    "minVersion": "5.0.0"
  },
  "deskpro": {
    "minVersion": "5.0.0"
  },
  "dev": {
    "minVersion": "5.4.0"
  },
  "deviantart": {
    "minVersion": "4.1.0"
  },
  "dhl": {
    "minVersion": "5.6.0"
  },
  "diaspora": {
    "minVersion": "5.6.0"
  },
  "digg": {
    "minVersion": "4.1.0"
  },
  "digital-ocean": {
    "minVersion": "5.0.0"
  },
  "discord": {
    "minVersion": "5.0.0"
  },
  "discourse": {
    "minVersion": "5.0.0"
  },
  "disqus": {
    "minVersion": "7.0.0"
  },
  "dochub": {
    "minVersion": "5.0.0"
  },
  "docker": {
    "minVersion": "5.0.0"
  },
  "draft2digital": {
    "minVersion": "5.0.0"
  },
  "dribbble": {
    "minVersion": "5.0.0"
  },
  "dropbox": {
    "minVersion": "3.2.0"
  },
  "drupal": {
    "minVersion": "4.1.0"
  },
  "duolingo": {
    "minVersion": "7.0.0"
  },
  "dyalog": {
    "minVersion": "5.0.0"
  },
  "earlybirds": {
    "minVersion": "5.0.0"
  },
  "ebay": {
    "minVersion": "5.0.11"
  },
  "edge": {
    "minVersion": "4.5.0"
  },
  "edge-legacy": {
    "minVersion": "5.13.1"
  },
  "elementor": {
    "minVersion": "5.0.3"
  },
  "eleventy": {
    "minVersion": "7.0.0"
  },
  "ello": {
    "minVersion": "5.2.0"
  },
  "ember": {
    "minVersion": "5.0.0"
  },
  "empire": {
    "minVersion": "4.1.0"
  },
  "envira": {
    "minVersion": "4.6.0"
  },
  "erlang": {
    "minVersion": "5.0.0"
  },
  "ethereum": {
    "minVersion": "5.0.2"
  },
  "etsy": {
    "minVersion": "4.7.0"
  },
  "evernote": {
    "minVersion": "5.8.0"
  },
  "expeditedssl": {
    "minVersion": "4.4.0"
  },
  "facebook": {
    "minVersion": "2.0.0"
  },
  "facebook-f": {
    "minVersion": "5.0.0"
  },
  "facebook-messenger": {
    "minVersion": "5.0.0"
  },
  "fantasy-flight-games": {
    "minVersion": "5.4.0"
  },
  "fedex": {
    "minVersion": "5.6.0"
  },
  "fediverse": {
    "minVersion": "7.2.0"
  },
  "fedora": {
    "minVersion": "5.6.0"
  },
  "figma": {
    "minVersion": "5.6.0"
  },
  "files-pinwheel": {
    "minVersion": "6.7.0"
  },
  "firefox": {
    "minVersion": "4.4.0"
  },
  "firefox-browser": {
    "minVersion": "5.12.0"
  },
  "first-order": {
    "minVersion": "4.6.0"
  },
  "first-order-alt": {
    "minVersion": "5.0.12"
  },
  "firstdraft": {
    "minVersion": "5.0.0"
  },
  "flickr": {
    "minVersion": "3.2.0"
  },
  "flipboard": {
    "minVersion": "5.0.5"
  },
  "flutter": {
    "minVersion": "6.6.0"
  },
  "fly": {
    "minVersion": "5.0.0"
  },
  "font-awesome": {
    "minVersion": "4.6.0"
  },
  "fonticons": {
    "minVersion": "4.4.0"
  },
  "fonticons-fi": {
    "minVersion": "5.0.0"
  },
  "forgejo": {
    "minVersion": "7.2.0"
  },
  "fort-awesome": {
    "minVersion": "4.5.0"
  },
  "fort-awesome-alt": {
    "minVersion": "5.0.0"
  },
  "forumbee": {
    "minVersion": "4.3.0"
  },
  "foursquare": {
    "minVersion": "3.2.0"
  },
  "free-code-camp": {
    "minVersion": "4.7.0"
  },
  "freebsd": {
    "minVersion": "5.0.0"
  },
  "fulcrum": {
    "minVersion": "5.0.12"
  },
  "galactic-republic": {
    "minVersion": "5.0.12"
  },
  "galactic-senate": {
    "minVersion": "5.0.12"
  },
  "get-pocket": {
    "minVersion": "4.4.0"
  },
  "gg": {
    "minVersion": "4.4.0"
  },
  "gg-circle": {
    "minVersion": "4.4.0"
  },
  "git": {
    "minVersion": "4.1.0"
  },
  "git-alt": {
    "minVersion": "5.8.2"
  },
  "gitee": {
    "minVersion": "7.2.0"
  },
  "github": {
    "minVersion": "2.0.0"
  },
  "github-alt": {
    "minVersion": "3.0.0"
  },
  "gitkraken": {
    "minVersion": "5.0.0"
  },
  "gitlab": {
    "minVersion": "4.6.0"
  },
  "gitter": {
    "minVersion": "5.0.0"
  },
  "glide": {
    "minVersion": "4.6.0"
  },
  "glide-g": {
    "minVersion": "4.6.0"
  },
  "globaleaks": {
    "minVersion": "7.2.0"
  },
  "gofore": {
    "minVersion": "5.0.0"
  },
  "golang": {
    "minVersion": "6.0.0-beta2"
  },
  "goodreads": {
    "minVersion": "5.0.0"
  },
  "goodreads-g": {
    "minVersion": "5.0.0"
  },
  "google": {
    "minVersion": "4.1.0"
  },
  "google-drive": {
    "minVersion": "5.0.0"
  },
  "google-pay": {
    "minVersion": "5.13.1"
  },
  "google-play": {
    "minVersion": "5.0.0"
  },
  "google-plus": {
    "minVersion": "4.6.0"
  },
  "google-plus-g": {
    "minVersion": "2.0.0"
  },
  "google-scholar": {
    "minVersion": "6.5.0"
  },
  "google-wallet": {
    "minVersion": "4.2.0"
  },
  "gratipay": {
    "minVersion": "3.2.0"
  },
  "grav": {
    "minVersion": "4.7.0"
  },
  "gripfire": {
    "minVersion": "5.0.0"
  },
  "grunt": {
    "minVersion": "5.0.0"
  },
  "guilded": {
    "minVersion": "5.15.0"
  },
  "gulp": {
    "minVersion": "5.0.0"
  },
  "hacker-news": {
    "minVersion": "4.1.0"
  },
  "hackerrank": {
    "minVersion": "5.2.0"
  },
  "hashnode": {
    "minVersion": "6.0.0"
  },
  "hips": {
    "minVersion": "5.0.5"
  },
  "hire-a-helper": {
    "minVersion": "5.0.0"
  },
  "hive": {
    "minVersion": "5.15.0"
  },
  "hooli": {
    "minVersion": "5.0.0"
  },
  "hornbill": {
    "minVersion": "5.1.0"
  },
  "hotjar": {
    "minVersion": "5.0.0"
  },
  "houzz": {
    "minVersion": "4.4.0"
  },
  "html5": {
    "minVersion": "3.1.0"
  },
  "hubspot": {
    "minVersion": "5.0.0"
  },
  "hugging-face": {
    "minVersion": "7.2.0"
  },
  "ideal": {
    "minVersion": "5.12.0"
  },
  "imdb": {
    "minVersion": "4.7.0"
  },
  "instagram": {
    "minVersion": "4.6.0"
  },
  "instalod": {
    "minVersion": "5.15.0"
  },
  "intercom": {
    "minVersion": "5.6.0"
  },
  "internet-explorer": {
    "minVersion": "4.4.0"
  },
  "invision": {
    "minVersion": "5.6.0"
  },
  "ioxhost": {
    "minVersion": "4.2.0"
  },
  "itch-io": {
    "minVersion": "5.8.0"
  },
  "itunes": {
    "minVersion": "5.0.0"
  },
  "itunes-note": {
    "minVersion": "5.0.0"
  },
  "java": {
    "minVersion": "5.0.10"
  },
  "jedi-order": {
    "minVersion": "5.0.12"
  },
  "jenkins": {
    "minVersion": "5.0.0"
  },
  "jira": {
    "minVersion": "5.6.0"
  },
  "joget": {
    "minVersion": "5.0.0"
  },
  "joomla": {
    "minVersion": "4.1.0"
  },
  "js": {
    "minVersion": "5.0.0"
  },
  "jsfiddle": {
    "minVersion": "4.1.0"
  },
  "julia": {
    "minVersion": "7.2.0"
  },
  "jxl": {
    "minVersion": "6.5.2"
  },
  "kaggle": {
    "minVersion": "5.2.0"
  },
  "kakao-talk": {
    "minVersion": "7.0.0"
  },
  "keybase": {
    "minVersion": "5.0.11"
  },
  "keycdn": {
    "minVersion": "5.0.0"
  },
  "kickstarter": {
    "minVersion": "5.0.0"
  },
  "kickstarter-k": {
    "minVersion": "5.0.0"
  },
  "ko-fi": {
    "minVersion": "7.2.0"
  },
  "korvue": {
    "minVersion": "5.0.2"
  },
  "kubernetes": {
    "minVersion": "7.2.0"
  },
  "laravel": {
    "minVersion": "5.0.0"
  },
  "lastfm": {
    "minVersion": "4.2.0"
  },
  "leanpub": {
    "minVersion": "4.3.0"
  },
  "leetcode": {
    "minVersion": "7.2.0"
  },
  "less": {
    "minVersion": "5.0.0"
  },
  "letterboxd": {
    "minVersion": "6.5.0"
  },
  "line": {
    "minVersion": "5.0.0"
  },
  "linkedin": {
    "minVersion": "1.0.0"
  },
  "linkedin-in": {
    "minVersion": "2.0.0"
  },
  "linktree": {
    "minVersion": "7.0.0"
  },
  "linode": {
    "minVersion": "4.7.0"
  },
  "linux": {
    "minVersion": "3.2.0"
  },
  "lumon": {
    "minVersion": "7.0.0"
  },
  "lumon-drop": {
    "minVersion": "7.0.0"
  },
  "lyft": {
    "minVersion": "5.0.0"
  },
  "magento": {
    "minVersion": "5.0.0"
  },
  "mailchimp": {
    "minVersion": "5.1.0"
  },
  "mandalorian": {
    "minVersion": "5.0.12"
  },
  "markdown": {
    "minVersion": "5.2.0"
  },
  "mastodon": {
    "minVersion": "5.0.11"
  },
  "maxcdn": {
    "minVersion": "3.1.0"
  },
  "mdb": {
    "minVersion": "5.11.0"
  },
  "medapps": {
    "minVersion": "5.0.0"
  },
  "medium": {
    "minVersion": "4.3.0"
  },
  "medrt": {
    "minVersion": "5.0.0"
  },
  "meetup": {
    "minVersion": "4.7.0"
  },
  "megaport": {
    "minVersion": "5.1.0"
  },
  "mendeley": {
    "minVersion": "5.6.0"
  },
  "meta": {
    "minVersion": "6.0.0"
  },
  "microblog": {
    "minVersion": "5.12.0"
  },
  "microsoft": {
    "minVersion": "5.0.0"
  },
  "mintbit": {
    "minVersion": "6.5.0"
  },
  "mix": {
    "minVersion": "5.0.0"
  },
  "mixcloud": {
    "minVersion": "4.5.0"
  },
  "mixer": {
    "minVersion": "5.12.1"
  },
  "mizuni": {
    "minVersion": "5.0.0"
  },
  "modx": {
    "minVersion": "4.5.0"
  },
  "monero": {
    "minVersion": "5.0.0"
  },
  "napster": {
    "minVersion": "5.0.0"
  },
  "neos": {
    "minVersion": "5.2.0"
  },
  "nfc-directional": {
    "minVersion": "6.1.0"
  },
  "nfc-symbol": {
    "minVersion": "6.1.0"
  },
  "nimblr": {
    "minVersion": "5.1.0"
  },
  "node": {
    "minVersion": "5.0.0"
  },
  "node-js": {
    "minVersion": "5.0.0"
  },
  "notion": {
    "minVersion": "7.0.0"
  },
  "npm": {
    "minVersion": "5.0.0"
  },
  "ns8": {
    "minVersion": "5.0.0"
  },
  "nutritionix": {
    "minVersion": "5.0.0"
  },
  "obsidian": {
    "minVersion": "7.2.0"
  },
  "octopus-deploy": {
    "minVersion": "5.15.0"
  },
  "odnoklassniki": {
    "minVersion": "4.4.0"
  },
  "odysee": {
    "minVersion": "6.2.1"
  },
  "old-republic": {
    "minVersion": "5.0.12"
  },
  "openai": {
    "minVersion": "7.0.0"
  },
  "opencart": {
    "minVersion": "4.4.0"
  },
  "openid": {
    "minVersion": "4.1.0"
  },
  "openstreetmap": {
    "minVersion": "7.2.0"
  },
  "opensuse": {
    "minVersion": "6.5.0"
  },
  "opera": {
    "minVersion": "4.4.0"
  },
  "optin-monster": {
    "minVersion": "4.4.0"
  },
  "orcid": {
    "minVersion": "5.11.0"
  },
  "osi": {
    "minVersion": "5.0.0"
  },
  "padlet": {
    "minVersion": "6.0.0"
  },
  "page4": {
    "minVersion": "5.0.0"
  },
  "pagelines": {
    "minVersion": "4.0.0"
  },
  "palfed": {
    "minVersion": "5.0.0"
  },
  "pandora": {
    "minVersion": "7.0.0"
  },
  "patreon": {
    "minVersion": "5.0.0"
  },
  "paypal": {
    "minVersion": "4.2.0"
  },
  "perbyte": {
    "minVersion": "5.15.0"
  },
  "periscope": {
    "minVersion": "5.0.0"
  },
  "phabricator": {
    "minVersion": "5.0.0"
  },
  "phoenix-framework": {
    "minVersion": "5.0.0"
  },
  "phoenix-squadron": {
    "minVersion": "5.0.12"
  },
  "php": {
    "minVersion": "5.0.5"
  },
  "pied-piper": {
    "minVersion": "4.6.0"
  },
  "pied-piper-alt": {
    "minVersion": "4.1.0"
  },
  "pied-piper-hat": {
    "minVersion": "5.0.10"
  },
  "pied-piper-pp": {
    "minVersion": "4.1.0"
  },
  "pinterest": {
    "minVersion": "2.0.0"
  },
  "pinterest-p": {
    "minVersion": "4.3.0"
  },
  "pix": {
    "minVersion": "6.0.0-beta2"
  },
  "pixelfed": {
    "minVersion": "7.0.0"
  },
  "pixiv": {
    "minVersion": "6.5.0"
  },
  "playstation": {
    "minVersion": "5.0.0"
  },
  "postgresql": {
    "minVersion": "7.2.0"
  },
  "product-hunt": {
    "minVersion": "4.5.0"
  },
  "pushed": {
    "minVersion": "5.0.0"
  },
  "python": {
    "minVersion": "5.0.0"
  },
  "qq": {
    "minVersion": "4.1.0"
  },
  "quinscape": {
    "minVersion": "5.0.5"
  },
  "quora": {
    "minVersion": "4.7.0"
  },
  "r-project": {
    "minVersion": "5.0.11"
  },
  "raspberry-pi": {
    "minVersion": "5.6.0"
  },
  "ravelry": {
    "minVersion": "4.7.0"
  },
  "react": {
    "minVersion": "5.0.0"
  },
  "reacteurope": {
    "minVersion": "5.5.0"
  },
  "readme": {
    "minVersion": "5.0.9"
  },
  "rebel": {
    "minVersion": "4.1.0"
  },
  "red-river": {
    "minVersion": "5.0.0"
  },
  "reddit": {
    "minVersion": "4.1.0"
  },
  "reddit-alien": {
    "minVersion": "4.5.0"
  },
  "redhat": {
    "minVersion": "5.6.0"
  },
  "renren": {
    "minVersion": "3.2.0"
  },
  "replyd": {
    "minVersion": "5.0.0"
  },
  "researchgate": {
    "minVersion": "5.0.11"
  },
  "resolving": {
    "minVersion": "5.0.0"
  },
  "rev": {
    "minVersion": "5.1.0"
  },
  "rocketchat": {
    "minVersion": "5.0.0"
  },
  "rockrms": {
    "minVersion": "5.0.0"
  },
  "rust": {
    "minVersion": "5.13.1"
  },
  "safari": {
    "minVersion": "4.4.0"
  },
  "salesforce": {
    "minVersion": "5.8.0"
  },
  "sass": {
    "minVersion": "5.0.0"
  },
  "scaleway": {
    "minVersion": "7.2.0"
  },
  "schlix": {
    "minVersion": "5.0.0"
  },
  "screenpal": {
    "minVersion": "6.1.0"
  },
  "scribd": {
    "minVersion": "4.5.0"
  },
  "searchengin": {
    "minVersion": "5.0.0"
  },
  "sellcast": {
    "minVersion": "5.0.0"
  },
  "sellsy": {
    "minVersion": "4.3.0"
  },
  "servicestack": {
    "minVersion": "5.0.0"
  },
  "shirtsinbulk": {
    "minVersion": "4.3.0"
  },
  "shoelace": {
    "minVersion": "6.4.1"
  },
  "shopify": {
    "minVersion": "5.12.1"
  },
  "shopware": {
    "minVersion": "5.1.0"
  },
  "signal-messenger": {
    "minVersion": "6.5.0"
  },
  "simplybuilt": {
    "minVersion": "4.3.0"
  },
  "sistrix": {
    "minVersion": "5.0.0"
  },
  "sith": {
    "minVersion": "5.0.12"
  },
  "sitrox": {
    "minVersion": "6.0.0-beta2"
  },
  "sketch": {
    "minVersion": "5.6.0"
  },
  "skyatlas": {
    "minVersion": "4.3.0"
  },
  "skype": {
    "minVersion": "3.2.0"
  },
  "slack": {
    "minVersion": "4.1.0"
  },
  "slideshare": {
    "minVersion": "4.2.0"
  },
  "snapchat": {
    "minVersion": "4.6.0"
  },
  "solana": {
    "minVersion": "7.2.0"
  },
  "soundcloud": {
    "minVersion": "4.1.0"
  },
  "sourcetree": {
    "minVersion": "5.6.0"
  },
  "space-awesome": {
    "minVersion": "6.1.2"
  },
  "speakap": {
    "minVersion": "5.0.0"
  },
  "speaker-deck": {
    "minVersion": "5.8.0"
  },
  "spotify": {
    "minVersion": "4.1.0"
  },
  "square-behance": {
    "minVersion": "4.1.0"
  },
  "square-bluesky": {
    "minVersion": "6.7.1"
  },
  "square-deskpro": {
    "minVersion": "7.2.0"
  },
  "square-dribbble": {
    "minVersion": "5.0.0"
  },
  "square-facebook": {
    "minVersion": "1.0.0"
  },
  "square-figma": {
    "minVersion": "7.0.0"
  },
  "square-font-awesome": {
    "minVersion": "5.0.0"
  },
  "square-font-awesome-stroke": {
    "minVersion": "5.0.0"
  },
  "square-git": {
    "minVersion": "4.1.0"
  },
  "square-github": {
    "minVersion": "1.0.0"
  },
  "square-gitlab": {
    "minVersion": "6.1.2"
  },
  "square-google-plus": {
    "minVersion": "2.0.0"
  },
  "square-hacker-news": {
    "minVersion": "5.0.0"
  },
  "square-instagram": {
    "minVersion": "5.12.1"
  },
  "square-js": {
    "minVersion": "5.0.0"
  },
  "square-lastfm": {
    "minVersion": "4.2.0"
  },
  "square-letterboxd": {
    "minVersion": "6.5.0"
  },
  "square-linkedin": {
    "minVersion": "7.0.0"
  },
  "square-odnoklassniki": {
    "minVersion": "4.4.0"
  },
  "square-pied-piper": {
    "minVersion": "5.12.0"
  },
  "square-pinterest": {
    "minVersion": "2.0.0"
  },
  "square-reddit": {
    "minVersion": "4.1.0"
  },
  "square-snapchat": {
    "minVersion": "4.6.0"
  },
  "square-steam": {
    "minVersion": "4.1.0"
  },
  "square-threads": {
    "minVersion": "6.4.1"
  },
  "square-tumblr": {
    "minVersion": "3.2.0"
  },
  "square-twitter": {
    "minVersion": "1.0.0"
  },
  "square-upwork": {
    "minVersion": "6.5.2"
  },
  "square-viadeo": {
    "minVersion": "4.6.0"
  },
  "square-vimeo": {
    "minVersion": "4.0.0"
  },
  "square-web-awesome": {
    "minVersion": "6.5.2"
  },
  "square-web-awesome-stroke": {
    "minVersion": "6.5.2"
  },
  "square-whatsapp": {
    "minVersion": "5.0.0"
  },
  "square-x-twitter": {
    "minVersion": "6.4.2"
  },
  "square-xing": {
    "minVersion": "3.2.0"
  },
  "square-youtube": {
    "minVersion": "5.0.3"
  },
  "squarespace": {
    "minVersion": "5.1.0"
  },
  "stack-exchange": {
    "minVersion": "4.0.0"
  },
  "stack-overflow": {
    "minVersion": "3.2.0"
  },
  "stackpath": {
    "minVersion": "5.8.2"
  },
  "staylinked": {
    "minVersion": "5.0.0"
  },
  "steam": {
    "minVersion": "4.1.0"
  },
  "steam-symbol": {
    "minVersion": "5.0.0"
  },
  "sticker-mule": {
    "minVersion": "5.0.0"
  },
  "strava": {
    "minVersion": "5.0.0"
  },
  "stripe": {
    "minVersion": "5.0.0"
  },
  "stripe-s": {
    "minVersion": "5.0.1"
  },
  "stubber": {
    "minVersion": "6.2.1"
  },
  "studiovinari": {
    "minVersion": "5.0.0"
  },
  "stumbleupon": {
    "minVersion": "4.1.0"
  },
  "stumbleupon-circle": {
    "minVersion": "4.1.0"
  },
  "superpowers": {
    "minVersion": "4.7.0"
  },
  "supple": {
    "minVersion": "5.0.0"
  },
  "supportnow": {
    "minVersion": "7.1.0"
  },
  "suse": {
    "minVersion": "5.6.0"
  },
  "svelte": {
    "minVersion": "7.2.0"
  },
  "swift": {
    "minVersion": "5.11.0"
  },
  "symfony": {
    "minVersion": "5.8.0"
  },
  "symfonycasts": {
    "minVersion": "7.2.0"
  },
  "tailwind-css": {
    "minVersion": "7.2.0"
  },
  "teamspeak": {
    "minVersion": "5.0.11"
  },
  "telegram": {
    "minVersion": "4.7.0"
  },
  "tencent-weibo": {
    "minVersion": "4.1.0"
  },
  "tex": {
    "minVersion": "7.0.0"
  },
  "the-red-yeti": {
    "minVersion": "5.3.0"
  },
  "themeco": {
    "minVersion": "5.1.0"
  },
  "themeisle": {
    "minVersion": "4.6.0"
  },
  "think-peaks": {
    "minVersion": "5.4.2"
  },
  "threads": {
    "minVersion": "6.4.1"
  },
  "threema": {
    "minVersion": "7.2.0"
  },
  "tidal": {
    "minVersion": "7.0.0"
  },
  "tiktok": {
    "minVersion": "5.13.1"
  },
  "tor-browser": {
    "minVersion": "7.1.0"
  },
  "trade-federation": {
    "minVersion": "5.0.12"
  },
  "trello": {
    "minVersion": "3.2.0"
  },
  "tumblr": {
    "minVersion": "3.2.0"
  },
  "twitch": {
    "minVersion": "4.2.0"
  },
  "twitter": {
    "minVersion": "2.0.0"
  },
  "typescript": {
    "minVersion": "7.2.0"
  },
  "typo3": {
    "minVersion": "5.0.1"
  },
  "uber": {
    "minVersion": "5.0.0"
  },
  "ubuntu": {
    "minVersion": "5.6.0"
  },
  "uikit": {
    "minVersion": "5.0.0"
  },
  "ultralytics": {
    "minVersion": "7.2.0"
  },
  "ultralytics-hub": {
    "minVersion": "7.2.0"
  },
  "ultralytics-yolo": {
    "minVersion": "7.2.0"
  },
  "umbraco": {
    "minVersion": "5.11.0"
  },
  "uncharted": {
    "minVersion": "5.15.0"
  },
  "uniregistry": {
    "minVersion": "5.0.0"
  },
  "unison": {
    "minVersion": "7.2.0"
  },
  "unity": {
    "minVersion": "5.12.0"
  },
  "unreal-engine": {
    "minVersion": "7.2.0"
  },
  "unsplash": {
    "minVersion": "5.13.1"
  },
  "untappd": {
    "minVersion": "5.0.0"
  },
  "ups": {
    "minVersion": "5.6.0"
  },
  "upwork": {
    "minVersion": "6.5.0"
  },
  "usb": {
    "minVersion": "4.5.0"
  },
  "usps": {
    "minVersion": "5.6.0"
  },
  "ussunnah": {
    "minVersion": "5.0.0"
  },
  "vaadin": {
    "minVersion": "5.0.0"
  },
  "venmo": {
    "minVersion": "7.2.0"
  },
  "venmo-v": {
    "minVersion": "7.2.0"
  },
  "viacoin": {
    "minVersion": "4.3.0"
  },
  "viadeo": {
    "minVersion": "4.6.0"
  },
  "viber": {
    "minVersion": "5.0.0"
  },
  "vim": {
    "minVersion": "7.2.0"
  },
  "vimeo": {
    "minVersion": "5.0.0"
  },
  "vimeo-v": {
    "minVersion": "4.4.0"
  },
  "vine": {
    "minVersion": "4.1.0"
  },
  "vk": {
    "minVersion": "3.2.0"
  },
  "vnv": {
    "minVersion": "5.0.0"
  },
  "vsco": {
    "minVersion": "7.0.0"
  },
  "vuejs": {
    "minVersion": "5.0.0"
  },
  "w3c": {
    "minVersion": "7.0.0"
  },
  "watchman-monitoring": {
    "minVersion": "5.15.0"
  },
  "waze": {
    "minVersion": "5.8.0"
  },
  "web-awesome": {
    "minVersion": "6.5.2"
  },
  "webflow": {
    "minVersion": "6.5.0"
  },
  "weebly": {
    "minVersion": "5.1.0"
  },
  "weibo": {
    "minVersion": "3.2.0"
  },
  "weixin": {
    "minVersion": "4.1.0"
  },
  "whatsapp": {
    "minVersion": "4.3.0"
  },
  "whmcs": {
    "minVersion": "5.0.0"
  },
  "wikipedia-w": {
    "minVersion": "4.4.0"
  },
  "windows": {
    "minVersion": "3.2.0"
  },
  "wirsindhandwerk": {
    "minVersion": "6.0.0-beta1"
  },
  "wix": {
    "minVersion": "5.1.0"
  },
  "wizards-of-the-coast": {
    "minVersion": "5.4.0"
  },
  "wodu": {
    "minVersion": "5.15.0"
  },
  "wolf-pack-battalion": {
    "minVersion": "5.0.12"
  },
  "wordpress": {
    "minVersion": "4.1.0"
  },
  "wordpress-simple": {
    "minVersion": "5.0.0"
  },
  "wpbeginner": {
    "minVersion": "4.6.0"
  },
  "wpexplorer": {
    "minVersion": "4.7.0"
  },
  "wpforms": {
    "minVersion": "4.6.0"
  },
  "wpressr": {
    "minVersion": "5.4.2"
  },
  "x-twitter": {
    "minVersion": "6.4.2"
  },
  "xbox": {
    "minVersion": "5.0.0"
  },
  "xing": {
    "minVersion": "3.2.0"
  },
  "xmpp": {
    "minVersion": "7.2.0"
  },
  "y-combinator": {
    "minVersion": "4.4.0"
  },
  "yahoo": {
    "minVersion": "4.1.0"
  },
  "yammer": {
    "minVersion": "5.8.0"
  },
  "yandex": {
    "minVersion": "5.0.0"
  },
  "yandex-international": {
    "minVersion": "5.0.0"
  },
  "yarn": {
    "minVersion": "5.6.0"
  },
  "yelp": {
    "minVersion": "4.2.0"
  },
  "yoast": {
    "minVersion": "4.6.0"
  },
  "youtube": {
    "minVersion": "3.2.0"
  },
  "zhihu": {
    "minVersion": "5.2.0"
  },
  "zoom": {
    "minVersion": "7.2.0"
  },
  "zulip": {
    "minVersion": "7.2.0"
  }
} as const

export default brandsIcons
