// This file is auto-generated by build/build.ts. Do not edit directly.

export const regularIcons = {
  "address-book": {
    "minVersion": "4.7.0"
  },
  "address-card": {
    "minVersion": "4.7.0"
  },
  "alarm-clock": {
    "minVersion": "5.0.0"
  },
  "bell": {
    "minVersion": "2.0.0"
  },
  "bell-slash": {
    "minVersion": "4.2.0"
  },
  "bookmark": {
    "minVersion": "1.0.0"
  },
  "building": {
    "minVersion": "4.1.0"
  },
  "calendar": {
    "minVersion": "3.1.0"
  },
  "calendar-check": {
    "minVersion": "4.4.0"
  },
  "calendar-days": {
    "minVersion": "1.0.0"
  },
  "calendar-minus": {
    "minVersion": "4.4.0"
  },
  "calendar-plus": {
    "minVersion": "4.4.0"
  },
  "calendar-xmark": {
    "minVersion": "4.4.0"
  },
  "camera": {
    "minVersion": "1.0.0"
  },
  "chart-bar": {
    "minVersion": "1.0.0"
  },
  "chess-bishop": {
    "minVersion": "5.0.5"
  },
  "chess-king": {
    "minVersion": "5.0.5"
  },
  "chess-knight": {
    "minVersion": "5.0.5"
  },
  "chess-pawn": {
    "minVersion": "5.0.5"
  },
  "chess-queen": {
    "minVersion": "5.0.5"
  },
  "chess-rook": {
    "minVersion": "5.0.5"
  },
  "circle": {
    "minVersion": "3.0.0"
  },
  "circle-check": {
    "minVersion": "1.0.0"
  },
  "circle-dot": {
    "minVersion": "4.0.0"
  },
  "circle-down": {
    "minVersion": "5.0.0"
  },
  "circle-left": {
    "minVersion": "5.0.0"
  },
  "circle-pause": {
    "minVersion": "4.5.0"
  },
  "circle-play": {
    "minVersion": "3.1.0"
  },
  "circle-question": {
    "minVersion": "1.0.0"
  },
  "circle-right": {
    "minVersion": "5.0.0"
  },
  "circle-stop": {
    "minVersion": "4.5.0"
  },
  "circle-up": {
    "minVersion": "5.0.0"
  },
  "circle-user": {
    "minVersion": "4.7.0"
  },
  "circle-xmark": {
    "minVersion": "1.0.0"
  },
  "clipboard": {
    "minVersion": "5.0.0"
  },
  "clock": {
    "minVersion": "1.0.0"
  },
  "clone": {
    "minVersion": "4.4.0"
  },
  "closed-captioning": {
    "minVersion": "4.2.0"
  },
  "cloud": {
    "minVersion": "2.0.0"
  },
  "comment": {
    "minVersion": "1.0.0"
  },
  "comment-dots": {
    "minVersion": "5.0.9"
  },
  "comments": {
    "minVersion": "1.0.0"
  },
  "compass": {
    "minVersion": "3.2.0"
  },
  "copy": {
    "minVersion": "2.0.0"
  },
  "copyright": {
    "minVersion": "4.2.0"
  },
  "credit-card": {
    "minVersion": "2.0.0"
  },
  "envelope": {
    "minVersion": "2.0.0"
  },
  "envelope-open": {
    "minVersion": "4.7.0"
  },
  "eye": {
    "minVersion": "1.0.0"
  },
  "eye-slash": {
    "minVersion": "1.0.0"
  },
  "face-angry": {
    "minVersion": "5.1.0"
  },
  "face-dizzy": {
    "minVersion": "5.1.0"
  },
  "face-flushed": {
    "minVersion": "5.1.0"
  },
  "face-frown": {
    "minVersion": "3.1.0"
  },
  "face-frown-open": {
    "minVersion": "5.1.0"
  },
  "face-grimace": {
    "minVersion": "5.1.0"
  },
  "face-grin": {
    "minVersion": "5.1.0"
  },
  "face-grin-beam": {
    "minVersion": "5.1.0"
  },
  "face-grin-beam-sweat": {
    "minVersion": "5.1.0"
  },
  "face-grin-hearts": {
    "minVersion": "5.1.0"
  },
  "face-grin-squint": {
    "minVersion": "5.1.0"
  },
  "face-grin-squint-tears": {
    "minVersion": "5.1.0"
  },
  "face-grin-stars": {
    "minVersion": "5.1.0"
  },
  "face-grin-tears": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue-squint": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue-wink": {
    "minVersion": "5.1.0"
  },
  "face-grin-wide": {
    "minVersion": "5.1.0"
  },
  "face-grin-wink": {
    "minVersion": "5.1.0"
  },
  "face-kiss": {
    "minVersion": "5.1.0"
  },
  "face-kiss-beam": {
    "minVersion": "5.1.0"
  },
  "face-kiss-wink-heart": {
    "minVersion": "5.1.0"
  },
  "face-laugh": {
    "minVersion": "5.1.0"
  },
  "face-laugh-beam": {
    "minVersion": "5.1.0"
  },
  "face-laugh-squint": {
    "minVersion": "5.1.0"
  },
  "face-laugh-wink": {
    "minVersion": "5.1.0"
  },
  "face-meh": {
    "minVersion": "3.1.0"
  },
  "face-meh-blank": {
    "minVersion": "5.1.0"
  },
  "face-rolling-eyes": {
    "minVersion": "5.1.0"
  },
  "face-sad-cry": {
    "minVersion": "5.1.0"
  },
  "face-sad-tear": {
    "minVersion": "5.1.0"
  },
  "face-smile": {
    "minVersion": "3.1.0"
  },
  "face-smile-beam": {
    "minVersion": "5.1.0"
  },
  "face-smile-wink": {
    "minVersion": "5.1.0"
  },
  "face-surprise": {
    "minVersion": "5.1.0"
  },
  "face-tired": {
    "minVersion": "5.1.0"
  },
  "file": {
    "minVersion": "3.2.0"
  },
  "file-audio": {
    "minVersion": "4.1.0"
  },
  "file-code": {
    "minVersion": "4.1.0"
  },
  "file-excel": {
    "minVersion": "4.1.0"
  },
  "file-image": {
    "minVersion": "4.1.0"
  },
  "file-lines": {
    "minVersion": "3.2.0"
  },
  "file-pdf": {
    "minVersion": "4.1.0"
  },
  "file-powerpoint": {
    "minVersion": "4.1.0"
  },
  "file-video": {
    "minVersion": "4.1.0"
  },
  "file-word": {
    "minVersion": "4.1.0"
  },
  "file-zipper": {
    "minVersion": "4.1.0"
  },
  "flag": {
    "minVersion": "1.0.0"
  },
  "floppy-disk": {
    "minVersion": "2.0.0"
  },
  "folder": {
    "minVersion": "1.0.0"
  },
  "folder-closed": {
    "minVersion": "6.0.0-beta1"
  },
  "folder-open": {
    "minVersion": "1.0.0"
  },
  "font-awesome": {
    "minVersion": "4.6.0"
  },
  "futbol": {
    "minVersion": "4.2.0"
  },
  "gem": {
    "minVersion": "5.0.0"
  },
  "hand": {
    "minVersion": "4.4.0"
  },
  "hand-back-fist": {
    "minVersion": "4.4.0"
  },
  "hand-lizard": {
    "minVersion": "4.4.0"
  },
  "hand-peace": {
    "minVersion": "4.4.0"
  },
  "hand-point-down": {
    "minVersion": "2.0.0"
  },
  "hand-point-left": {
    "minVersion": "2.0.0"
  },
  "hand-point-right": {
    "minVersion": "2.0.0"
  },
  "hand-point-up": {
    "minVersion": "2.0.0"
  },
  "hand-pointer": {
    "minVersion": "4.4.0"
  },
  "hand-scissors": {
    "minVersion": "4.4.0"
  },
  "hand-spock": {
    "minVersion": "4.4.0"
  },
  "handshake": {
    "minVersion": "4.7.0"
  },
  "hard-drive": {
    "minVersion": "2.0.0"
  },
  "headphones": {
    "minVersion": "1.0.0"
  },
  "heart": {
    "minVersion": "1.0.0"
  },
  "hospital": {
    "minVersion": "3.0.0"
  },
  "hourglass": {
    "minVersion": "4.4.0"
  },
  "hourglass-half": {
    "minVersion": "4.4.0"
  },
  "house": {
    "minVersion": "1.0.0"
  },
  "id-badge": {
    "minVersion": "4.7.0"
  },
  "id-card": {
    "minVersion": "4.7.0"
  },
  "image": {
    "minVersion": "1.0.0"
  },
  "images": {
    "minVersion": "1.0.0"
  },
  "keyboard": {
    "minVersion": "3.1.0"
  },
  "lemon": {
    "minVersion": "1.0.0"
  },
  "life-ring": {
    "minVersion": "4.1.0"
  },
  "lightbulb": {
    "minVersion": "3.0.0"
  },
  "map": {
    "minVersion": "4.4.0"
  },
  "message": {
    "minVersion": "4.4.0"
  },
  "money-bill-1": {
    "minVersion": "5.0.0"
  },
  "moon": {
    "minVersion": "3.2.0"
  },
  "newspaper": {
    "minVersion": "4.2.0"
  },
  "note-sticky": {
    "minVersion": "4.4.0"
  },
  "object-group": {
    "minVersion": "4.4.0"
  },
  "object-ungroup": {
    "minVersion": "4.4.0"
  },
  "paper-plane": {
    "minVersion": "4.1.0"
  },
  "paste": {
    "minVersion": "2.0.0"
  },
  "pen-to-square": {
    "minVersion": "1.0.0"
  },
  "rectangle-list": {
    "minVersion": "1.0.0"
  },
  "rectangle-xmark": {
    "minVersion": "4.7.0"
  },
  "registered": {
    "minVersion": "4.4.0"
  },
  "share-from-square": {
    "minVersion": "3.1.0"
  },
  "snowflake": {
    "minVersion": "4.7.0"
  },
  "square": {
    "minVersion": "2.0.0"
  },
  "square-caret-down": {
    "minVersion": "3.2.0"
  },
  "square-caret-left": {
    "minVersion": "4.0.0"
  },
  "square-caret-right": {
    "minVersion": "3.2.0"
  },
  "square-caret-up": {
    "minVersion": "3.2.0"
  },
  "square-check": {
    "minVersion": "3.1.0"
  },
  "square-full": {
    "minVersion": "5.0.5"
  },
  "square-minus": {
    "minVersion": "3.1.0"
  },
  "square-plus": {
    "minVersion": "3.0.0"
  },
  "star": {
    "minVersion": "1.0.0"
  },
  "star-half": {
    "minVersion": "1.0.0"
  },
  "star-half-stroke": {
    "minVersion": "5.1.0"
  },
  "sun": {
    "minVersion": "3.2.0"
  },
  "thumbs-down": {
    "minVersion": "3.2.0"
  },
  "thumbs-up": {
    "minVersion": "3.2.0"
  },
  "trash-can": {
    "minVersion": "5.0.0"
  },
  "truck": {
    "minVersion": "2.0.0"
  },
  "user": {
    "minVersion": "1.0.0"
  },
  "window-maximize": {
    "minVersion": "4.7.0"
  },
  "window-minimize": {
    "minVersion": "4.7.0"
  },
  "window-restore": {
    "minVersion": "4.7.0"
  }
} as const

export default regularIcons
