// This file is auto-generated by build/build.ts. Do not edit directly.

export const solidIcons = {
  "0": {
    "minVersion": "6.0.0-beta1"
  },
  "1": {
    "minVersion": "6.0.0-beta1"
  },
  "2": {
    "minVersion": "6.0.0-beta1"
  },
  "3": {
    "minVersion": "6.0.0-beta1"
  },
  "4": {
    "minVersion": "6.0.0-beta1"
  },
  "5": {
    "minVersion": "6.0.0-beta1"
  },
  "6": {
    "minVersion": "6.0.0-beta1"
  },
  "7": {
    "minVersion": "6.0.0-beta1"
  },
  "8": {
    "minVersion": "6.0.0-beta1"
  },
  "9": {
    "minVersion": "6.0.0-beta1"
  },
  "a": {
    "minVersion": "6.0.0-beta1"
  },
  "address-book": {
    "minVersion": "4.7.0"
  },
  "address-card": {
    "minVersion": "4.7.0"
  },
  "alarm-clock": {
    "minVersion": "5.0.0"
  },
  "align-center": {
    "minVersion": "1.0.0"
  },
  "align-justify": {
    "minVersion": "1.0.0"
  },
  "align-left": {
    "minVersion": "1.0.0"
  },
  "align-right": {
    "minVersion": "1.0.0"
  },
  "anchor": {
    "minVersion": "3.1.0"
  },
  "anchor-circle-check": {
    "minVersion": "6.1.0"
  },
  "anchor-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "anchor-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "anchor-lock": {
    "minVersion": "6.1.0"
  },
  "angle-down": {
    "minVersion": "3.0.0"
  },
  "angle-left": {
    "minVersion": "3.0.0"
  },
  "angle-right": {
    "minVersion": "3.0.0"
  },
  "angle-up": {
    "minVersion": "3.0.0"
  },
  "angles-down": {
    "minVersion": "3.0.0"
  },
  "angles-left": {
    "minVersion": "3.0.0"
  },
  "angles-right": {
    "minVersion": "3.0.0"
  },
  "angles-up": {
    "minVersion": "3.0.0"
  },
  "ankh": {
    "minVersion": "5.3.0"
  },
  "apple-whole": {
    "minVersion": "5.2.0"
  },
  "aquarius": {
    "minVersion": "7.2.0"
  },
  "archway": {
    "minVersion": "5.1.0"
  },
  "aries": {
    "minVersion": "7.2.0"
  },
  "arrow-down": {
    "minVersion": "1.0.0"
  },
  "arrow-down-1-9": {
    "minVersion": "3.2.0"
  },
  "arrow-down-9-1": {
    "minVersion": "5.9.0"
  },
  "arrow-down-a-z": {
    "minVersion": "3.2.0"
  },
  "arrow-down-long": {
    "minVersion": "3.2.0"
  },
  "arrow-down-short-wide": {
    "minVersion": "5.9.0"
  },
  "arrow-down-up-across-line": {
    "minVersion": "6.1.0"
  },
  "arrow-down-up-lock": {
    "minVersion": "6.1.0"
  },
  "arrow-down-wide-short": {
    "minVersion": "3.2.0"
  },
  "arrow-down-z-a": {
    "minVersion": "5.9.0"
  },
  "arrow-left": {
    "minVersion": "1.0.0"
  },
  "arrow-left-long": {
    "minVersion": "3.2.0"
  },
  "arrow-pointer": {
    "minVersion": "4.4.0"
  },
  "arrow-right": {
    "minVersion": "1.0.0"
  },
  "arrow-right-arrow-left": {
    "minVersion": "3.0.0"
  },
  "arrow-right-from-bracket": {
    "minVersion": "1.0.0"
  },
  "arrow-right-long": {
    "minVersion": "3.2.0"
  },
  "arrow-right-to-bracket": {
    "minVersion": "1.0.0"
  },
  "arrow-right-to-city": {
    "minVersion": "6.1.0"
  },
  "arrow-rotate-left": {
    "minVersion": "2.0.0"
  },
  "arrow-rotate-right": {
    "minVersion": "1.0.0"
  },
  "arrow-trend-down": {
    "minVersion": "6.0.0-beta1"
  },
  "arrow-trend-up": {
    "minVersion": "6.0.0-beta1"
  },
  "arrow-turn-down": {
    "minVersion": "3.1.0"
  },
  "arrow-turn-up": {
    "minVersion": "3.1.0"
  },
  "arrow-up": {
    "minVersion": "1.0.0"
  },
  "arrow-up-1-9": {
    "minVersion": "3.2.0"
  },
  "arrow-up-9-1": {
    "minVersion": "5.9.0"
  },
  "arrow-up-a-z": {
    "minVersion": "3.2.0"
  },
  "arrow-up-from-bracket": {
    "minVersion": "6.0.0-beta1"
  },
  "arrow-up-from-ground-water": {
    "minVersion": "6.1.0"
  },
  "arrow-up-from-water-pump": {
    "minVersion": "6.1.0"
  },
  "arrow-up-long": {
    "minVersion": "3.2.0"
  },
  "arrow-up-right-dots": {
    "minVersion": "6.1.0"
  },
  "arrow-up-right-from-square": {
    "minVersion": "1.0.0"
  },
  "arrow-up-short-wide": {
    "minVersion": "5.9.0"
  },
  "arrow-up-wide-short": {
    "minVersion": "3.2.0"
  },
  "arrow-up-z-a": {
    "minVersion": "5.9.0"
  },
  "arrows-down-to-line": {
    "minVersion": "6.1.0"
  },
  "arrows-down-to-people": {
    "minVersion": "6.1.0"
  },
  "arrows-left-right": {
    "minVersion": "1.0.0"
  },
  "arrows-left-right-to-line": {
    "minVersion": "6.1.0"
  },
  "arrows-rotate": {
    "minVersion": "1.0.0"
  },
  "arrows-spin": {
    "minVersion": "6.1.0"
  },
  "arrows-split-up-and-left": {
    "minVersion": "6.1.0"
  },
  "arrows-to-circle": {
    "minVersion": "6.1.0"
  },
  "arrows-to-dot": {
    "minVersion": "6.1.0"
  },
  "arrows-to-eye": {
    "minVersion": "6.1.0"
  },
  "arrows-turn-right": {
    "minVersion": "6.1.0"
  },
  "arrows-turn-to-dots": {
    "minVersion": "6.1.0"
  },
  "arrows-up-down": {
    "minVersion": "1.0.0"
  },
  "arrows-up-down-left-right": {
    "minVersion": "1.0.0"
  },
  "arrows-up-to-line": {
    "minVersion": "6.1.0"
  },
  "asterisk": {
    "minVersion": "1.0.0"
  },
  "at": {
    "minVersion": "4.2.0"
  },
  "atom": {
    "minVersion": "5.2.0"
  },
  "audio-description": {
    "minVersion": "4.6.0"
  },
  "austral-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "award": {
    "minVersion": "5.1.0"
  },
  "b": {
    "minVersion": "6.0.0-beta1"
  },
  "baby": {
    "minVersion": "5.6.0"
  },
  "baby-carriage": {
    "minVersion": "5.6.0"
  },
  "backward": {
    "minVersion": "1.0.0"
  },
  "backward-fast": {
    "minVersion": "1.0.0"
  },
  "backward-step": {
    "minVersion": "1.0.0"
  },
  "bacon": {
    "minVersion": "5.7.0"
  },
  "bacteria": {
    "minVersion": "5.13.0"
  },
  "bacterium": {
    "minVersion": "5.13.0"
  },
  "bag-shopping": {
    "minVersion": "4.5.0"
  },
  "bahai": {
    "minVersion": "5.3.0"
  },
  "baht-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "ban": {
    "minVersion": "1.0.0"
  },
  "ban-smoking": {
    "minVersion": "5.0.13"
  },
  "bandage": {
    "minVersion": "5.0.7"
  },
  "bangladeshi-taka-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "barcode": {
    "minVersion": "1.0.0"
  },
  "bars": {
    "minVersion": "2.0.0"
  },
  "bars-progress": {
    "minVersion": "5.7.0"
  },
  "bars-staggered": {
    "minVersion": "5.0.13"
  },
  "baseball": {
    "minVersion": "5.0.5"
  },
  "baseball-bat-ball": {
    "minVersion": "5.0.5"
  },
  "basket-shopping": {
    "minVersion": "4.5.0"
  },
  "basketball": {
    "minVersion": "5.0.5"
  },
  "bath": {
    "minVersion": "4.7.0"
  },
  "battery-empty": {
    "minVersion": "4.4.0"
  },
  "battery-full": {
    "minVersion": "4.4.0"
  },
  "battery-half": {
    "minVersion": "4.4.0"
  },
  "battery-quarter": {
    "minVersion": "4.4.0"
  },
  "battery-three-quarters": {
    "minVersion": "4.4.0"
  },
  "bed": {
    "minVersion": "4.3.0"
  },
  "bed-pulse": {
    "minVersion": "5.0.7"
  },
  "beer-mug-empty": {
    "minVersion": "3.0.0"
  },
  "bell": {
    "minVersion": "2.0.0"
  },
  "bell-concierge": {
    "minVersion": "5.1.0"
  },
  "bell-slash": {
    "minVersion": "4.2.0"
  },
  "bezier-curve": {
    "minVersion": "5.1.0"
  },
  "bicycle": {
    "minVersion": "4.2.0"
  },
  "binoculars": {
    "minVersion": "4.2.0"
  },
  "biohazard": {
    "minVersion": "5.6.0"
  },
  "bitcoin-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "blender": {
    "minVersion": "5.0.13"
  },
  "blender-phone": {
    "minVersion": "5.4.0"
  },
  "blog": {
    "minVersion": "5.6.0"
  },
  "bold": {
    "minVersion": "1.0.0"
  },
  "bolt": {
    "minVersion": "2.0.0"
  },
  "bolt-lightning": {
    "minVersion": "6.0.0-beta1"
  },
  "bomb": {
    "minVersion": "4.1.0"
  },
  "bone": {
    "minVersion": "5.2.0"
  },
  "bong": {
    "minVersion": "5.1.0"
  },
  "book": {
    "minVersion": "1.0.0"
  },
  "book-atlas": {
    "minVersion": "5.1.0"
  },
  "book-bible": {
    "minVersion": "5.3.0"
  },
  "book-bookmark": {
    "minVersion": "6.0.0-beta1"
  },
  "book-journal-whills": {
    "minVersion": "5.3.0"
  },
  "book-medical": {
    "minVersion": "5.7.0"
  },
  "book-open": {
    "minVersion": "5.0.13"
  },
  "book-open-reader": {
    "minVersion": "5.2.0"
  },
  "book-quran": {
    "minVersion": "5.3.0"
  },
  "book-skull": {
    "minVersion": "5.4.0"
  },
  "book-tanakh": {
    "minVersion": "5.7.0"
  },
  "bookmark": {
    "minVersion": "1.0.0"
  },
  "border-all": {
    "minVersion": "5.9.0"
  },
  "border-none": {
    "minVersion": "5.9.0"
  },
  "border-top-left": {
    "minVersion": "5.9.0"
  },
  "bore-hole": {
    "minVersion": "6.1.0"
  },
  "bottle-droplet": {
    "minVersion": "6.1.0"
  },
  "bottle-water": {
    "minVersion": "6.1.0"
  },
  "bowl-food": {
    "minVersion": "6.1.0"
  },
  "bowl-rice": {
    "minVersion": "6.0.0-beta1"
  },
  "bowling-ball": {
    "minVersion": "5.0.5"
  },
  "box": {
    "minVersion": "5.0.7"
  },
  "box-archive": {
    "minVersion": "3.2.0"
  },
  "box-open": {
    "minVersion": "5.0.9"
  },
  "box-tissue": {
    "minVersion": "5.13.0"
  },
  "boxes-packing": {
    "minVersion": "6.1.0"
  },
  "boxes-stacked": {
    "minVersion": "5.0.7"
  },
  "braille": {
    "minVersion": "4.6.0"
  },
  "brain": {
    "minVersion": "5.2.0"
  },
  "brazilian-real-sign": {
    "minVersion": "6.0.0-beta3"
  },
  "bread-slice": {
    "minVersion": "5.7.0"
  },
  "bridge": {
    "minVersion": "6.1.0"
  },
  "bridge-circle-check": {
    "minVersion": "6.1.0"
  },
  "bridge-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "bridge-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "bridge-lock": {
    "minVersion": "6.1.0"
  },
  "bridge-water": {
    "minVersion": "6.1.0"
  },
  "briefcase": {
    "minVersion": "2.0.0"
  },
  "briefcase-medical": {
    "minVersion": "5.0.7"
  },
  "broom": {
    "minVersion": "5.0.13"
  },
  "broom-ball": {
    "minVersion": "5.0.5"
  },
  "brush": {
    "minVersion": "5.1.0"
  },
  "bucket": {
    "minVersion": "6.1.0"
  },
  "bug": {
    "minVersion": "3.2.0"
  },
  "bug-slash": {
    "minVersion": "6.0.0"
  },
  "bugs": {
    "minVersion": "6.1.0"
  },
  "building": {
    "minVersion": "4.1.0"
  },
  "building-circle-arrow-right": {
    "minVersion": "6.1.0"
  },
  "building-circle-check": {
    "minVersion": "6.1.0"
  },
  "building-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "building-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "building-columns": {
    "minVersion": "4.1.0"
  },
  "building-flag": {
    "minVersion": "6.1.0"
  },
  "building-lock": {
    "minVersion": "6.1.0"
  },
  "building-ngo": {
    "minVersion": "6.1.0"
  },
  "building-shield": {
    "minVersion": "6.1.0"
  },
  "building-un": {
    "minVersion": "6.1.0"
  },
  "building-user": {
    "minVersion": "6.1.0"
  },
  "building-wheat": {
    "minVersion": "6.1.0"
  },
  "bullhorn": {
    "minVersion": "2.0.0"
  },
  "bullseye": {
    "minVersion": "3.1.0"
  },
  "burger": {
    "minVersion": "5.7.0"
  },
  "burst": {
    "minVersion": "6.1.0"
  },
  "bus": {
    "minVersion": "4.2.0"
  },
  "bus-side": {
    "minVersion": "7.0.0"
  },
  "bus-simple": {
    "minVersion": "5.1.0"
  },
  "business-time": {
    "minVersion": "5.3.0"
  },
  "c": {
    "minVersion": "6.0.0-beta1"
  },
  "cable-car": {
    "minVersion": "6.0.0-beta1"
  },
  "cake-candles": {
    "minVersion": "4.2.0"
  },
  "calculator": {
    "minVersion": "4.2.0"
  },
  "calendar": {
    "minVersion": "3.1.0"
  },
  "calendar-check": {
    "minVersion": "4.4.0"
  },
  "calendar-day": {
    "minVersion": "5.6.0"
  },
  "calendar-days": {
    "minVersion": "1.0.0"
  },
  "calendar-minus": {
    "minVersion": "4.4.0"
  },
  "calendar-plus": {
    "minVersion": "4.4.0"
  },
  "calendar-week": {
    "minVersion": "5.6.0"
  },
  "calendar-xmark": {
    "minVersion": "4.4.0"
  },
  "camera": {
    "minVersion": "1.0.0"
  },
  "camera-retro": {
    "minVersion": "1.0.0"
  },
  "camera-rotate": {
    "minVersion": "6.0.0-beta1"
  },
  "campground": {
    "minVersion": "5.4.0"
  },
  "cancer": {
    "minVersion": "7.2.0"
  },
  "candy-cane": {
    "minVersion": "5.6.0"
  },
  "cannabis": {
    "minVersion": "5.1.0"
  },
  "capricorn": {
    "minVersion": "7.2.0"
  },
  "capsules": {
    "minVersion": "5.0.7"
  },
  "car": {
    "minVersion": "4.1.0"
  },
  "car-battery": {
    "minVersion": "5.2.0"
  },
  "car-burst": {
    "minVersion": "5.2.0"
  },
  "car-on": {
    "minVersion": "6.1.0"
  },
  "car-rear": {
    "minVersion": "5.2.0"
  },
  "car-side": {
    "minVersion": "5.2.0"
  },
  "car-tunnel": {
    "minVersion": "6.1.0"
  },
  "caravan": {
    "minVersion": "5.12.0"
  },
  "caret-down": {
    "minVersion": "2.0.0"
  },
  "caret-left": {
    "minVersion": "2.0.0"
  },
  "caret-right": {
    "minVersion": "2.0.0"
  },
  "caret-up": {
    "minVersion": "2.0.0"
  },
  "carrot": {
    "minVersion": "5.6.0"
  },
  "cart-arrow-down": {
    "minVersion": "4.3.0"
  },
  "cart-flatbed": {
    "minVersion": "5.0.7"
  },
  "cart-flatbed-suitcase": {
    "minVersion": "5.1.0"
  },
  "cart-plus": {
    "minVersion": "4.3.0"
  },
  "cart-shopping": {
    "minVersion": "1.0.0"
  },
  "cash-register": {
    "minVersion": "5.6.0"
  },
  "cat": {
    "minVersion": "5.4.0"
  },
  "cedi-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "cent-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "certificate": {
    "minVersion": "2.0.0"
  },
  "chair": {
    "minVersion": "5.4.0"
  },
  "chalkboard": {
    "minVersion": "5.0.13"
  },
  "chalkboard-user": {
    "minVersion": "5.0.13"
  },
  "champagne-glasses": {
    "minVersion": "5.6.0"
  },
  "charging-station": {
    "minVersion": "5.2.0"
  },
  "chart-area": {
    "minVersion": "4.2.0"
  },
  "chart-bar": {
    "minVersion": "1.0.0"
  },
  "chart-column": {
    "minVersion": "6.0.0-beta1"
  },
  "chart-diagram": {
    "minVersion": "6.7.0"
  },
  "chart-gantt": {
    "minVersion": "6.0.0-beta1"
  },
  "chart-line": {
    "minVersion": "4.2.0"
  },
  "chart-pie": {
    "minVersion": "4.2.0"
  },
  "chart-simple": {
    "minVersion": "6.0.0-beta3"
  },
  "check": {
    "minVersion": "1.0.0"
  },
  "check-double": {
    "minVersion": "5.1.0"
  },
  "check-to-slot": {
    "minVersion": "5.5.0"
  },
  "cheese": {
    "minVersion": "5.7.0"
  },
  "chess": {
    "minVersion": "5.0.5"
  },
  "chess-bishop": {
    "minVersion": "5.0.5"
  },
  "chess-board": {
    "minVersion": "5.0.5"
  },
  "chess-king": {
    "minVersion": "5.0.5"
  },
  "chess-knight": {
    "minVersion": "5.0.5"
  },
  "chess-pawn": {
    "minVersion": "5.0.5"
  },
  "chess-queen": {
    "minVersion": "5.0.5"
  },
  "chess-rook": {
    "minVersion": "5.0.5"
  },
  "chevron-down": {
    "minVersion": "1.0.0"
  },
  "chevron-left": {
    "minVersion": "1.0.0"
  },
  "chevron-right": {
    "minVersion": "1.0.0"
  },
  "chevron-up": {
    "minVersion": "1.0.0"
  },
  "child": {
    "minVersion": "4.1.0"
  },
  "child-combatant": {
    "minVersion": "6.1.0"
  },
  "child-dress": {
    "minVersion": "6.1.1"
  },
  "child-reaching": {
    "minVersion": "6.1.1"
  },
  "children": {
    "minVersion": "6.1.0"
  },
  "church": {
    "minVersion": "5.0.13"
  },
  "circle": {
    "minVersion": "3.0.0"
  },
  "circle-arrow-down": {
    "minVersion": "2.0.0"
  },
  "circle-arrow-left": {
    "minVersion": "2.0.0"
  },
  "circle-arrow-right": {
    "minVersion": "2.0.0"
  },
  "circle-arrow-up": {
    "minVersion": "2.0.0"
  },
  "circle-check": {
    "minVersion": "1.0.0"
  },
  "circle-chevron-down": {
    "minVersion": "3.1.0"
  },
  "circle-chevron-left": {
    "minVersion": "3.1.0"
  },
  "circle-chevron-right": {
    "minVersion": "3.1.0"
  },
  "circle-chevron-up": {
    "minVersion": "3.1.0"
  },
  "circle-dollar-to-slot": {
    "minVersion": "5.0.9"
  },
  "circle-dot": {
    "minVersion": "4.0.0"
  },
  "circle-down": {
    "minVersion": "5.0.0"
  },
  "circle-exclamation": {
    "minVersion": "1.0.0"
  },
  "circle-h": {
    "minVersion": "5.0.7"
  },
  "circle-half-stroke": {
    "minVersion": "1.0.0"
  },
  "circle-info": {
    "minVersion": "1.0.0"
  },
  "circle-left": {
    "minVersion": "5.0.0"
  },
  "circle-minus": {
    "minVersion": "1.0.0"
  },
  "circle-nodes": {
    "minVersion": "6.1.0"
  },
  "circle-notch": {
    "minVersion": "4.1.0"
  },
  "circle-pause": {
    "minVersion": "4.5.0"
  },
  "circle-play": {
    "minVersion": "3.1.0"
  },
  "circle-plus": {
    "minVersion": "1.0.0"
  },
  "circle-question": {
    "minVersion": "1.0.0"
  },
  "circle-radiation": {
    "minVersion": "5.6.0"
  },
  "circle-right": {
    "minVersion": "5.0.0"
  },
  "circle-stop": {
    "minVersion": "4.5.0"
  },
  "circle-up": {
    "minVersion": "5.0.0"
  },
  "circle-user": {
    "minVersion": "4.7.0"
  },
  "circle-xmark": {
    "minVersion": "1.0.0"
  },
  "city": {
    "minVersion": "5.3.0"
  },
  "clapperboard": {
    "minVersion": "6.0.0-beta1"
  },
  "clipboard": {
    "minVersion": "5.0.0"
  },
  "clipboard-check": {
    "minVersion": "5.0.7"
  },
  "clipboard-list": {
    "minVersion": "5.0.7"
  },
  "clipboard-question": {
    "minVersion": "6.1.0"
  },
  "clipboard-user": {
    "minVersion": "5.7.0"
  },
  "clock": {
    "minVersion": "1.0.0"
  },
  "clock-rotate-left": {
    "minVersion": "4.1.0"
  },
  "clone": {
    "minVersion": "4.4.0"
  },
  "closed-captioning": {
    "minVersion": "4.2.0"
  },
  "closed-captioning-slash": {
    "minVersion": "6.0.0-beta1"
  },
  "cloud": {
    "minVersion": "2.0.0"
  },
  "cloud-arrow-down": {
    "minVersion": "3.0.0"
  },
  "cloud-arrow-up": {
    "minVersion": "3.0.0"
  },
  "cloud-bolt": {
    "minVersion": "5.5.0"
  },
  "cloud-meatball": {
    "minVersion": "5.5.0"
  },
  "cloud-moon": {
    "minVersion": "5.4.0"
  },
  "cloud-moon-rain": {
    "minVersion": "5.5.0"
  },
  "cloud-rain": {
    "minVersion": "5.5.0"
  },
  "cloud-showers-heavy": {
    "minVersion": "5.5.0"
  },
  "cloud-showers-water": {
    "minVersion": "6.1.0"
  },
  "cloud-sun": {
    "minVersion": "5.4.0"
  },
  "cloud-sun-rain": {
    "minVersion": "5.5.0"
  },
  "clover": {
    "minVersion": "6.0.0-beta1"
  },
  "code": {
    "minVersion": "3.1.0"
  },
  "code-branch": {
    "minVersion": "5.0.0"
  },
  "code-commit": {
    "minVersion": "5.0.0"
  },
  "code-compare": {
    "minVersion": "6.0.0-beta1"
  },
  "code-fork": {
    "minVersion": "6.0.0-beta1"
  },
  "code-merge": {
    "minVersion": "5.0.0"
  },
  "code-pull-request": {
    "minVersion": "6.0.0-beta1"
  },
  "coins": {
    "minVersion": "5.0.13"
  },
  "colon-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "comment": {
    "minVersion": "1.0.0"
  },
  "comment-dollar": {
    "minVersion": "5.3.0"
  },
  "comment-dots": {
    "minVersion": "5.0.9"
  },
  "comment-medical": {
    "minVersion": "5.7.0"
  },
  "comment-nodes": {
    "minVersion": "6.7.0"
  },
  "comment-slash": {
    "minVersion": "5.0.9"
  },
  "comment-sms": {
    "minVersion": "5.6.0"
  },
  "comments": {
    "minVersion": "1.0.0"
  },
  "comments-dollar": {
    "minVersion": "5.3.0"
  },
  "compact-disc": {
    "minVersion": "5.0.13"
  },
  "compass": {
    "minVersion": "3.2.0"
  },
  "compass-drafting": {
    "minVersion": "5.1.0"
  },
  "compress": {
    "minVersion": "5.0.0"
  },
  "computer": {
    "minVersion": "6.1.0"
  },
  "computer-mouse": {
    "minVersion": "5.11.0"
  },
  "cookie": {
    "minVersion": "5.1.0"
  },
  "cookie-bite": {
    "minVersion": "5.1.0"
  },
  "copy": {
    "minVersion": "2.0.0"
  },
  "copyright": {
    "minVersion": "4.2.0"
  },
  "couch": {
    "minVersion": "5.0.9"
  },
  "cow": {
    "minVersion": "5.4.0"
  },
  "credit-card": {
    "minVersion": "2.0.0"
  },
  "crop": {
    "minVersion": "3.1.0"
  },
  "crop-simple": {
    "minVersion": "5.1.0"
  },
  "cross": {
    "minVersion": "5.3.0"
  },
  "crosshairs": {
    "minVersion": "1.0.0"
  },
  "crow": {
    "minVersion": "5.0.13"
  },
  "crown": {
    "minVersion": "5.0.13"
  },
  "crutch": {
    "minVersion": "5.7.0"
  },
  "cruzeiro-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "cube": {
    "minVersion": "4.1.0"
  },
  "cubes": {
    "minVersion": "4.1.0"
  },
  "cubes-stacked": {
    "minVersion": "6.1.0"
  },
  "d": {
    "minVersion": "6.0.0-beta1"
  },
  "database": {
    "minVersion": "4.1.0"
  },
  "delete-left": {
    "minVersion": "5.1.0"
  },
  "democrat": {
    "minVersion": "5.5.0"
  },
  "desktop": {
    "minVersion": "3.0.0"
  },
  "dharmachakra": {
    "minVersion": "5.3.0"
  },
  "diagram-next": {
    "minVersion": "6.0.0-beta3"
  },
  "diagram-predecessor": {
    "minVersion": "6.0.0-beta3"
  },
  "diagram-project": {
    "minVersion": "5.0.13"
  },
  "diagram-successor": {
    "minVersion": "6.0.0-beta3"
  },
  "diamond": {
    "minVersion": "4.3.0"
  },
  "diamond-turn-right": {
    "minVersion": "5.2.0"
  },
  "dice": {
    "minVersion": "5.0.13"
  },
  "dice-d20": {
    "minVersion": "5.4.0"
  },
  "dice-d6": {
    "minVersion": "5.4.0"
  },
  "dice-five": {
    "minVersion": "5.0.13"
  },
  "dice-four": {
    "minVersion": "5.0.13"
  },
  "dice-one": {
    "minVersion": "5.0.13"
  },
  "dice-six": {
    "minVersion": "5.0.13"
  },
  "dice-three": {
    "minVersion": "5.0.13"
  },
  "dice-two": {
    "minVersion": "5.0.13"
  },
  "disease": {
    "minVersion": "5.7.0"
  },
  "display": {
    "minVersion": "6.0.0-beta1"
  },
  "divide": {
    "minVersion": "5.0.13"
  },
  "dna": {
    "minVersion": "5.0.7"
  },
  "dog": {
    "minVersion": "5.4.0"
  },
  "dollar-sign": {
    "minVersion": "3.2.0"
  },
  "dolly": {
    "minVersion": "5.0.7"
  },
  "dong-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "door-closed": {
    "minVersion": "5.0.13"
  },
  "door-open": {
    "minVersion": "5.0.13"
  },
  "dove": {
    "minVersion": "5.0.9"
  },
  "down-left-and-up-right-to-center": {
    "minVersion": "1.0.0"
  },
  "down-long": {
    "minVersion": "5.0.0"
  },
  "download": {
    "minVersion": "1.0.0"
  },
  "dragon": {
    "minVersion": "5.4.0"
  },
  "draw-polygon": {
    "minVersion": "5.2.0"
  },
  "droplet": {
    "minVersion": "1.0.0"
  },
  "droplet-slash": {
    "minVersion": "5.1.0"
  },
  "drum": {
    "minVersion": "5.1.0"
  },
  "drum-steelpan": {
    "minVersion": "5.1.0"
  },
  "drumstick-bite": {
    "minVersion": "5.4.0"
  },
  "dumbbell": {
    "minVersion": "5.0.5"
  },
  "dumpster": {
    "minVersion": "5.6.0"
  },
  "dumpster-fire": {
    "minVersion": "5.6.0"
  },
  "dungeon": {
    "minVersion": "5.4.0"
  },
  "e": {
    "minVersion": "6.0.0-beta1"
  },
  "ear-deaf": {
    "minVersion": "4.6.0"
  },
  "ear-listen": {
    "minVersion": "4.6.0"
  },
  "earth-africa": {
    "minVersion": "5.1.0"
  },
  "earth-americas": {
    "minVersion": "5.1.0"
  },
  "earth-asia": {
    "minVersion": "5.1.0"
  },
  "earth-europe": {
    "minVersion": "5.6.0"
  },
  "earth-oceania": {
    "minVersion": "6.0.0-beta3"
  },
  "egg": {
    "minVersion": "5.7.0"
  },
  "eject": {
    "minVersion": "1.0.0"
  },
  "elevator": {
    "minVersion": "6.0.0-beta1"
  },
  "ellipsis": {
    "minVersion": "3.1.0"
  },
  "ellipsis-vertical": {
    "minVersion": "3.1.0"
  },
  "envelope": {
    "minVersion": "2.0.0"
  },
  "envelope-circle-check": {
    "minVersion": "6.1.0"
  },
  "envelope-open": {
    "minVersion": "4.7.0"
  },
  "envelope-open-text": {
    "minVersion": "5.3.0"
  },
  "envelopes-bulk": {
    "minVersion": "5.3.0"
  },
  "equals": {
    "minVersion": "5.0.13"
  },
  "eraser": {
    "minVersion": "3.1.0"
  },
  "ethernet": {
    "minVersion": "5.6.0"
  },
  "euro-sign": {
    "minVersion": "3.2.0"
  },
  "exclamation": {
    "minVersion": "3.1.0"
  },
  "expand": {
    "minVersion": "5.0.0"
  },
  "explosion": {
    "minVersion": "6.1.0"
  },
  "eye": {
    "minVersion": "1.0.0"
  },
  "eye-dropper": {
    "minVersion": "4.2.0"
  },
  "eye-low-vision": {
    "minVersion": "4.6.0"
  },
  "eye-slash": {
    "minVersion": "1.0.0"
  },
  "f": {
    "minVersion": "6.0.0-beta1"
  },
  "face-angry": {
    "minVersion": "5.1.0"
  },
  "face-dizzy": {
    "minVersion": "5.1.0"
  },
  "face-flushed": {
    "minVersion": "5.1.0"
  },
  "face-frown": {
    "minVersion": "3.1.0"
  },
  "face-frown-open": {
    "minVersion": "5.1.0"
  },
  "face-grimace": {
    "minVersion": "5.1.0"
  },
  "face-grin": {
    "minVersion": "5.1.0"
  },
  "face-grin-beam": {
    "minVersion": "5.1.0"
  },
  "face-grin-beam-sweat": {
    "minVersion": "5.1.0"
  },
  "face-grin-hearts": {
    "minVersion": "5.1.0"
  },
  "face-grin-squint": {
    "minVersion": "5.1.0"
  },
  "face-grin-squint-tears": {
    "minVersion": "5.1.0"
  },
  "face-grin-stars": {
    "minVersion": "5.1.0"
  },
  "face-grin-tears": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue-squint": {
    "minVersion": "5.1.0"
  },
  "face-grin-tongue-wink": {
    "minVersion": "5.1.0"
  },
  "face-grin-wide": {
    "minVersion": "5.1.0"
  },
  "face-grin-wink": {
    "minVersion": "5.1.0"
  },
  "face-kiss": {
    "minVersion": "5.1.0"
  },
  "face-kiss-beam": {
    "minVersion": "5.1.0"
  },
  "face-kiss-wink-heart": {
    "minVersion": "5.1.0"
  },
  "face-laugh": {
    "minVersion": "5.1.0"
  },
  "face-laugh-beam": {
    "minVersion": "5.1.0"
  },
  "face-laugh-squint": {
    "minVersion": "5.1.0"
  },
  "face-laugh-wink": {
    "minVersion": "5.1.0"
  },
  "face-meh": {
    "minVersion": "3.1.0"
  },
  "face-meh-blank": {
    "minVersion": "5.1.0"
  },
  "face-rolling-eyes": {
    "minVersion": "5.1.0"
  },
  "face-sad-cry": {
    "minVersion": "5.1.0"
  },
  "face-sad-tear": {
    "minVersion": "5.1.0"
  },
  "face-smile": {
    "minVersion": "3.1.0"
  },
  "face-smile-beam": {
    "minVersion": "5.1.0"
  },
  "face-smile-wink": {
    "minVersion": "5.1.0"
  },
  "face-surprise": {
    "minVersion": "5.1.0"
  },
  "face-tired": {
    "minVersion": "5.1.0"
  },
  "fan": {
    "minVersion": "5.9.0"
  },
  "faucet": {
    "minVersion": "5.12.0"
  },
  "faucet-drip": {
    "minVersion": "5.12.0"
  },
  "fax": {
    "minVersion": "4.1.0"
  },
  "feather": {
    "minVersion": "5.0.13"
  },
  "feather-pointed": {
    "minVersion": "5.1.0"
  },
  "ferry": {
    "minVersion": "6.1.0"
  },
  "file": {
    "minVersion": "3.2.0"
  },
  "file-arrow-down": {
    "minVersion": "5.1.0"
  },
  "file-arrow-up": {
    "minVersion": "5.1.0"
  },
  "file-audio": {
    "minVersion": "4.1.0"
  },
  "file-circle-check": {
    "minVersion": "6.0.0"
  },
  "file-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "file-circle-minus": {
    "minVersion": "6.1.0"
  },
  "file-circle-plus": {
    "minVersion": "6.0.0"
  },
  "file-circle-question": {
    "minVersion": "6.1.0"
  },
  "file-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "file-code": {
    "minVersion": "4.1.0"
  },
  "file-contract": {
    "minVersion": "5.1.0"
  },
  "file-csv": {
    "minVersion": "5.4.0"
  },
  "file-excel": {
    "minVersion": "4.1.0"
  },
  "file-export": {
    "minVersion": "5.1.0"
  },
  "file-fragment": {
    "minVersion": "6.7.0"
  },
  "file-half-dashed": {
    "minVersion": "6.7.0"
  },
  "file-image": {
    "minVersion": "4.1.0"
  },
  "file-import": {
    "minVersion": "5.1.0"
  },
  "file-invoice": {
    "minVersion": "5.1.0"
  },
  "file-invoice-dollar": {
    "minVersion": "5.1.0"
  },
  "file-lines": {
    "minVersion": "3.2.0"
  },
  "file-medical": {
    "minVersion": "5.0.7"
  },
  "file-pdf": {
    "minVersion": "4.1.0"
  },
  "file-pen": {
    "minVersion": "5.0.0"
  },
  "file-powerpoint": {
    "minVersion": "4.1.0"
  },
  "file-prescription": {
    "minVersion": "5.1.0"
  },
  "file-shield": {
    "minVersion": "6.1.0"
  },
  "file-signature": {
    "minVersion": "5.1.0"
  },
  "file-video": {
    "minVersion": "4.1.0"
  },
  "file-waveform": {
    "minVersion": "5.0.7"
  },
  "file-word": {
    "minVersion": "4.1.0"
  },
  "file-zipper": {
    "minVersion": "4.1.0"
  },
  "fill": {
    "minVersion": "5.1.0"
  },
  "fill-drip": {
    "minVersion": "5.1.0"
  },
  "film": {
    "minVersion": "1.0.0"
  },
  "filter": {
    "minVersion": "2.0.0"
  },
  "filter-circle-dollar": {
    "minVersion": "5.3.0"
  },
  "filter-circle-xmark": {
    "minVersion": "6.0.0-beta1"
  },
  "fingerprint": {
    "minVersion": "5.1.0"
  },
  "fire": {
    "minVersion": "1.0.0"
  },
  "fire-burner": {
    "minVersion": "6.1.0"
  },
  "fire-extinguisher": {
    "minVersion": "3.1.0"
  },
  "fire-flame-curved": {
    "minVersion": "5.6.3"
  },
  "fire-flame-simple": {
    "minVersion": "5.0.7"
  },
  "fish": {
    "minVersion": "5.1.0"
  },
  "fish-fins": {
    "minVersion": "6.1.0"
  },
  "flag": {
    "minVersion": "1.0.0"
  },
  "flag-checkered": {
    "minVersion": "3.1.0"
  },
  "flag-usa": {
    "minVersion": "5.5.0"
  },
  "flask": {
    "minVersion": "2.0.0"
  },
  "flask-vial": {
    "minVersion": "6.1.0"
  },
  "floppy-disk": {
    "minVersion": "2.0.0"
  },
  "florin-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "folder": {
    "minVersion": "1.0.0"
  },
  "folder-closed": {
    "minVersion": "6.0.0-beta1"
  },
  "folder-minus": {
    "minVersion": "5.3.0"
  },
  "folder-open": {
    "minVersion": "1.0.0"
  },
  "folder-plus": {
    "minVersion": "5.3.0"
  },
  "folder-tree": {
    "minVersion": "5.7.0"
  },
  "font": {
    "minVersion": "1.0.0"
  },
  "font-awesome": {
    "minVersion": "4.6.0"
  },
  "football": {
    "minVersion": "5.0.5"
  },
  "forward": {
    "minVersion": "1.0.0"
  },
  "forward-fast": {
    "minVersion": "1.0.0"
  },
  "forward-step": {
    "minVersion": "1.0.0"
  },
  "franc-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "frog": {
    "minVersion": "5.0.13"
  },
  "futbol": {
    "minVersion": "4.2.0"
  },
  "g": {
    "minVersion": "6.0.0-beta1"
  },
  "gamepad": {
    "minVersion": "3.1.0"
  },
  "gas-pump": {
    "minVersion": "5.0.13"
  },
  "gauge": {
    "minVersion": "5.2.0"
  },
  "gauge-high": {
    "minVersion": "5.2.0"
  },
  "gauge-simple": {
    "minVersion": "5.2.0"
  },
  "gauge-simple-high": {
    "minVersion": "5.2.0"
  },
  "gavel": {
    "minVersion": "2.0.0"
  },
  "gear": {
    "minVersion": "1.0.0"
  },
  "gears": {
    "minVersion": "1.0.0"
  },
  "gem": {
    "minVersion": "5.0.0"
  },
  "gemini": {
    "minVersion": "7.2.0"
  },
  "genderless": {
    "minVersion": "4.4.0"
  },
  "ghost": {
    "minVersion": "5.4.0"
  },
  "gift": {
    "minVersion": "1.0.0"
  },
  "gifts": {
    "minVersion": "5.6.0"
  },
  "glass-water": {
    "minVersion": "6.1.0"
  },
  "glass-water-droplet": {
    "minVersion": "6.1.0"
  },
  "glasses": {
    "minVersion": "5.0.13"
  },
  "globe": {
    "minVersion": "2.0.0"
  },
  "golf-ball-tee": {
    "minVersion": "5.0.5"
  },
  "gopuram": {
    "minVersion": "5.3.0"
  },
  "graduation-cap": {
    "minVersion": "4.1.0"
  },
  "greater-than": {
    "minVersion": "5.0.13"
  },
  "greater-than-equal": {
    "minVersion": "5.0.13"
  },
  "grip": {
    "minVersion": "5.1.0"
  },
  "grip-lines": {
    "minVersion": "5.6.0"
  },
  "grip-lines-vertical": {
    "minVersion": "5.6.0"
  },
  "grip-vertical": {
    "minVersion": "5.1.0"
  },
  "group-arrows-rotate": {
    "minVersion": "6.1.0"
  },
  "guarani-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "guitar": {
    "minVersion": "5.6.0"
  },
  "gun": {
    "minVersion": "6.0.0-beta1"
  },
  "h": {
    "minVersion": "6.0.0-beta1"
  },
  "hammer": {
    "minVersion": "5.4.0"
  },
  "hamsa": {
    "minVersion": "5.3.0"
  },
  "hand": {
    "minVersion": "4.4.0"
  },
  "hand-back-fist": {
    "minVersion": "4.4.0"
  },
  "hand-dots": {
    "minVersion": "5.0.7"
  },
  "hand-fist": {
    "minVersion": "5.4.0"
  },
  "hand-holding": {
    "minVersion": "5.0.9"
  },
  "hand-holding-dollar": {
    "minVersion": "5.0.9"
  },
  "hand-holding-droplet": {
    "minVersion": "5.0.9"
  },
  "hand-holding-hand": {
    "minVersion": "6.1.0"
  },
  "hand-holding-heart": {
    "minVersion": "5.0.9"
  },
  "hand-holding-medical": {
    "minVersion": "5.13.0"
  },
  "hand-lizard": {
    "minVersion": "4.4.0"
  },
  "hand-middle-finger": {
    "minVersion": "5.7.0"
  },
  "hand-peace": {
    "minVersion": "4.4.0"
  },
  "hand-point-down": {
    "minVersion": "2.0.0"
  },
  "hand-point-left": {
    "minVersion": "2.0.0"
  },
  "hand-point-right": {
    "minVersion": "2.0.0"
  },
  "hand-point-up": {
    "minVersion": "2.0.0"
  },
  "hand-pointer": {
    "minVersion": "4.4.0"
  },
  "hand-scissors": {
    "minVersion": "4.4.0"
  },
  "hand-sparkles": {
    "minVersion": "5.13.0"
  },
  "hand-spock": {
    "minVersion": "4.4.0"
  },
  "handcuffs": {
    "minVersion": "6.1.0"
  },
  "hands": {
    "minVersion": "4.6.0"
  },
  "hands-asl-interpreting": {
    "minVersion": "4.6.0"
  },
  "hands-bound": {
    "minVersion": "6.1.0"
  },
  "hands-bubbles": {
    "minVersion": "5.13.0"
  },
  "hands-clapping": {
    "minVersion": "6.0.0-beta1"
  },
  "hands-holding": {
    "minVersion": "5.0.9"
  },
  "hands-holding-child": {
    "minVersion": "6.1.0"
  },
  "hands-holding-circle": {
    "minVersion": "6.1.0"
  },
  "hands-praying": {
    "minVersion": "5.3.0"
  },
  "handshake": {
    "minVersion": "4.7.0"
  },
  "handshake-angle": {
    "minVersion": "5.0.9"
  },
  "handshake-slash": {
    "minVersion": "5.13.0"
  },
  "hanukiah": {
    "minVersion": "5.4.0"
  },
  "hard-drive": {
    "minVersion": "2.0.0"
  },
  "hashtag": {
    "minVersion": "4.5.0"
  },
  "hat-cowboy": {
    "minVersion": "5.11.0"
  },
  "hat-cowboy-side": {
    "minVersion": "5.11.0"
  },
  "hat-wizard": {
    "minVersion": "5.4.0"
  },
  "head-side-cough": {
    "minVersion": "5.13.0"
  },
  "head-side-cough-slash": {
    "minVersion": "5.13.0"
  },
  "head-side-mask": {
    "minVersion": "5.13.0"
  },
  "head-side-virus": {
    "minVersion": "5.13.0"
  },
  "heading": {
    "minVersion": "4.1.0"
  },
  "headphones": {
    "minVersion": "1.0.0"
  },
  "headset": {
    "minVersion": "5.1.0"
  },
  "heart": {
    "minVersion": "1.0.0"
  },
  "heart-circle-bolt": {
    "minVersion": "6.1.0"
  },
  "heart-circle-check": {
    "minVersion": "6.1.0"
  },
  "heart-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "heart-circle-minus": {
    "minVersion": "6.1.0"
  },
  "heart-circle-plus": {
    "minVersion": "6.1.0"
  },
  "heart-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "heart-crack": {
    "minVersion": "5.6.0"
  },
  "heart-pulse": {
    "minVersion": "4.3.0"
  },
  "helicopter": {
    "minVersion": "5.0.13"
  },
  "helicopter-symbol": {
    "minVersion": "6.1.0"
  },
  "helmet-safety": {
    "minVersion": "5.7.0"
  },
  "helmet-un": {
    "minVersion": "6.1.0"
  },
  "hexagon": {
    "minVersion": "5.0.0"
  },
  "hexagon-nodes": {
    "minVersion": "6.7.0"
  },
  "hexagon-nodes-bolt": {
    "minVersion": "6.7.0"
  },
  "highlighter": {
    "minVersion": "5.1.0"
  },
  "hill-avalanche": {
    "minVersion": "6.1.0"
  },
  "hill-rockslide": {
    "minVersion": "6.1.0"
  },
  "hippo": {
    "minVersion": "5.4.0"
  },
  "hockey-puck": {
    "minVersion": "5.0.5"
  },
  "holly-berry": {
    "minVersion": "5.6.0"
  },
  "horse": {
    "minVersion": "5.4.0"
  },
  "horse-head": {
    "minVersion": "5.6.0"
  },
  "hospital": {
    "minVersion": "3.0.0"
  },
  "hospital-user": {
    "minVersion": "5.7.0"
  },
  "hot-tub-person": {
    "minVersion": "5.1.0"
  },
  "hotdog": {
    "minVersion": "5.7.0"
  },
  "hotel": {
    "minVersion": "5.1.0"
  },
  "hourglass": {
    "minVersion": "4.4.0"
  },
  "hourglass-end": {
    "minVersion": "4.4.0"
  },
  "hourglass-half": {
    "minVersion": "4.4.0"
  },
  "hourglass-start": {
    "minVersion": "4.4.0"
  },
  "house": {
    "minVersion": "1.0.0"
  },
  "house-chimney": {
    "minVersion": "6.0.0-beta1"
  },
  "house-chimney-crack": {
    "minVersion": "5.4.0"
  },
  "house-chimney-medical": {
    "minVersion": "5.7.0"
  },
  "house-chimney-user": {
    "minVersion": "5.13.0"
  },
  "house-chimney-window": {
    "minVersion": "5.12.0"
  },
  "house-circle-check": {
    "minVersion": "6.1.0"
  },
  "house-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "house-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "house-crack": {
    "minVersion": "6.0.0-beta1"
  },
  "house-fire": {
    "minVersion": "6.1.0"
  },
  "house-flag": {
    "minVersion": "6.1.0"
  },
  "house-flood-water": {
    "minVersion": "6.1.0"
  },
  "house-flood-water-circle-arrow-right": {
    "minVersion": "6.1.0"
  },
  "house-laptop": {
    "minVersion": "5.13.0"
  },
  "house-lock": {
    "minVersion": "6.1.0"
  },
  "house-medical": {
    "minVersion": "6.0.0-beta1"
  },
  "house-medical-circle-check": {
    "minVersion": "6.1.0"
  },
  "house-medical-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "house-medical-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "house-medical-flag": {
    "minVersion": "6.1.0"
  },
  "house-signal": {
    "minVersion": "5.12.0"
  },
  "house-tsunami": {
    "minVersion": "6.1.0"
  },
  "house-user": {
    "minVersion": "6.0.0-beta1"
  },
  "hryvnia-sign": {
    "minVersion": "5.4.0"
  },
  "hurricane": {
    "minVersion": "5.5.0"
  },
  "i": {
    "minVersion": "6.0.0-beta1"
  },
  "i-cursor": {
    "minVersion": "4.4.0"
  },
  "ice-cream": {
    "minVersion": "5.7.0"
  },
  "icicles": {
    "minVersion": "5.6.0"
  },
  "icons": {
    "minVersion": "5.9.0"
  },
  "id-badge": {
    "minVersion": "4.7.0"
  },
  "id-card": {
    "minVersion": "4.7.0"
  },
  "id-card-clip": {
    "minVersion": "5.0.7"
  },
  "igloo": {
    "minVersion": "5.6.0"
  },
  "image": {
    "minVersion": "1.0.0"
  },
  "image-portrait": {
    "minVersion": "5.0.0"
  },
  "images": {
    "minVersion": "1.0.0"
  },
  "inbox": {
    "minVersion": "1.0.0"
  },
  "indent": {
    "minVersion": "1.0.0"
  },
  "indian-rupee-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "industry": {
    "minVersion": "4.4.0"
  },
  "infinity": {
    "minVersion": "5.0.13"
  },
  "info": {
    "minVersion": "3.1.0"
  },
  "italic": {
    "minVersion": "1.0.0"
  },
  "j": {
    "minVersion": "6.0.0-beta1"
  },
  "jar": {
    "minVersion": "6.1.0"
  },
  "jar-wheat": {
    "minVersion": "6.1.0"
  },
  "jedi": {
    "minVersion": "5.3.0"
  },
  "jet-fighter": {
    "minVersion": "3.0.0"
  },
  "jet-fighter-up": {
    "minVersion": "6.1.0"
  },
  "joint": {
    "minVersion": "5.1.0"
  },
  "jug-detergent": {
    "minVersion": "6.1.0"
  },
  "k": {
    "minVersion": "6.0.0-beta1"
  },
  "kaaba": {
    "minVersion": "5.3.0"
  },
  "key": {
    "minVersion": "1.0.0"
  },
  "keyboard": {
    "minVersion": "3.1.0"
  },
  "khanda": {
    "minVersion": "5.3.0"
  },
  "kip-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "kit-medical": {
    "minVersion": "5.0.7"
  },
  "kitchen-set": {
    "minVersion": "6.1.0"
  },
  "kiwi-bird": {
    "minVersion": "5.0.13"
  },
  "l": {
    "minVersion": "6.0.0-beta1"
  },
  "land-mine-on": {
    "minVersion": "6.1.0"
  },
  "landmark": {
    "minVersion": "5.3.0"
  },
  "landmark-dome": {
    "minVersion": "5.5.0"
  },
  "landmark-flag": {
    "minVersion": "6.1.0"
  },
  "language": {
    "minVersion": "4.1.0"
  },
  "laptop": {
    "minVersion": "3.0.0"
  },
  "laptop-code": {
    "minVersion": "5.2.0"
  },
  "laptop-file": {
    "minVersion": "6.1.0"
  },
  "laptop-medical": {
    "minVersion": "5.7.0"
  },
  "lari-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "layer-group": {
    "minVersion": "5.2.0"
  },
  "leaf": {
    "minVersion": "1.0.0"
  },
  "left-long": {
    "minVersion": "5.0.0"
  },
  "left-right": {
    "minVersion": "5.0.0"
  },
  "lemon": {
    "minVersion": "1.0.0"
  },
  "leo": {
    "minVersion": "7.2.0"
  },
  "less-than": {
    "minVersion": "5.0.13"
  },
  "less-than-equal": {
    "minVersion": "5.0.13"
  },
  "libra": {
    "minVersion": "7.2.0"
  },
  "life-ring": {
    "minVersion": "4.1.0"
  },
  "lightbulb": {
    "minVersion": "3.0.0"
  },
  "lines-leaning": {
    "minVersion": "6.1.0"
  },
  "link": {
    "minVersion": "2.0.0"
  },
  "link-slash": {
    "minVersion": "3.1.0"
  },
  "lira-sign": {
    "minVersion": "4.0.0"
  },
  "list": {
    "minVersion": "1.0.0"
  },
  "list-check": {
    "minVersion": "2.0.0"
  },
  "list-ol": {
    "minVersion": "2.0.0"
  },
  "list-ul": {
    "minVersion": "2.0.0"
  },
  "litecoin-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "location-arrow": {
    "minVersion": "3.1.0"
  },
  "location-crosshairs": {
    "minVersion": "5.2.0"
  },
  "location-dot": {
    "minVersion": "5.0.0"
  },
  "location-pin": {
    "minVersion": "1.0.0"
  },
  "location-pin-lock": {
    "minVersion": "6.1.0"
  },
  "lock": {
    "minVersion": "1.0.0"
  },
  "lock-open": {
    "minVersion": "3.1.0"
  },
  "locust": {
    "minVersion": "6.1.0"
  },
  "lungs": {
    "minVersion": "5.2.0"
  },
  "lungs-virus": {
    "minVersion": "5.13.0"
  },
  "m": {
    "minVersion": "6.0.0-beta1"
  },
  "magnet": {
    "minVersion": "1.0.0"
  },
  "magnifying-glass": {
    "minVersion": "1.0.0"
  },
  "magnifying-glass-arrow-right": {
    "minVersion": "6.1.0"
  },
  "magnifying-glass-chart": {
    "minVersion": "6.1.0"
  },
  "magnifying-glass-dollar": {
    "minVersion": "5.3.0"
  },
  "magnifying-glass-location": {
    "minVersion": "5.3.0"
  },
  "magnifying-glass-minus": {
    "minVersion": "1.0.0"
  },
  "magnifying-glass-plus": {
    "minVersion": "1.0.0"
  },
  "manat-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "map": {
    "minVersion": "4.4.0"
  },
  "map-location": {
    "minVersion": "5.1.0"
  },
  "map-location-dot": {
    "minVersion": "5.1.0"
  },
  "map-pin": {
    "minVersion": "4.4.0"
  },
  "marker": {
    "minVersion": "5.1.0"
  },
  "mars": {
    "minVersion": "4.3.0"
  },
  "mars-and-venus": {
    "minVersion": "4.3.0"
  },
  "mars-and-venus-burst": {
    "minVersion": "6.1.0"
  },
  "mars-double": {
    "minVersion": "4.3.0"
  },
  "mars-stroke": {
    "minVersion": "4.3.0"
  },
  "mars-stroke-right": {
    "minVersion": "4.3.0"
  },
  "mars-stroke-up": {
    "minVersion": "4.3.0"
  },
  "martini-glass": {
    "minVersion": "5.1.0"
  },
  "martini-glass-citrus": {
    "minVersion": "5.1.0"
  },
  "martini-glass-empty": {
    "minVersion": "1.0.0"
  },
  "mask": {
    "minVersion": "5.4.0"
  },
  "mask-face": {
    "minVersion": "6.0.0-beta1"
  },
  "mask-ventilator": {
    "minVersion": "6.1.0"
  },
  "masks-theater": {
    "minVersion": "5.2.0"
  },
  "mattress-pillow": {
    "minVersion": "6.1.0"
  },
  "maximize": {
    "minVersion": "5.0.0"
  },
  "medal": {
    "minVersion": "5.1.0"
  },
  "memory": {
    "minVersion": "5.0.13"
  },
  "menorah": {
    "minVersion": "5.3.0"
  },
  "mercury": {
    "minVersion": "4.3.0"
  },
  "message": {
    "minVersion": "4.4.0"
  },
  "meteor": {
    "minVersion": "5.5.0"
  },
  "microchip": {
    "minVersion": "4.7.0"
  },
  "microphone": {
    "minVersion": "3.1.0"
  },
  "microphone-lines": {
    "minVersion": "5.0.0"
  },
  "microphone-lines-slash": {
    "minVersion": "5.0.13"
  },
  "microphone-slash": {
    "minVersion": "3.1.0"
  },
  "microscope": {
    "minVersion": "5.2.0"
  },
  "mill-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "minimize": {
    "minVersion": "5.6.0"
  },
  "minus": {
    "minVersion": "1.0.0"
  },
  "mitten": {
    "minVersion": "5.6.0"
  },
  "mobile": {
    "minVersion": "5.0.0"
  },
  "mobile-button": {
    "minVersion": "3.0.0"
  },
  "mobile-retro": {
    "minVersion": "6.1.0"
  },
  "mobile-screen": {
    "minVersion": "5.0.0"
  },
  "mobile-screen-button": {
    "minVersion": "5.0.0"
  },
  "mobile-vibrate": {
    "minVersion": "7.0.0"
  },
  "money-bill": {
    "minVersion": "2.0.0"
  },
  "money-bill-1": {
    "minVersion": "5.0.0"
  },
  "money-bill-1-wave": {
    "minVersion": "5.0.13"
  },
  "money-bill-transfer": {
    "minVersion": "6.1.0"
  },
  "money-bill-trend-up": {
    "minVersion": "6.1.0"
  },
  "money-bill-wave": {
    "minVersion": "5.0.13"
  },
  "money-bill-wheat": {
    "minVersion": "6.1.0"
  },
  "money-bills": {
    "minVersion": "6.0.0-beta1"
  },
  "money-check": {
    "minVersion": "5.0.13"
  },
  "money-check-dollar": {
    "minVersion": "5.0.13"
  },
  "monument": {
    "minVersion": "5.1.0"
  },
  "moon": {
    "minVersion": "3.2.0"
  },
  "mortar-pestle": {
    "minVersion": "5.1.0"
  },
  "mosque": {
    "minVersion": "5.3.0"
  },
  "mosquito": {
    "minVersion": "6.1.0"
  },
  "mosquito-net": {
    "minVersion": "6.1.0"
  },
  "motorcycle": {
    "minVersion": "4.3.0"
  },
  "mound": {
    "minVersion": "6.1.0"
  },
  "mountain": {
    "minVersion": "5.4.0"
  },
  "mountain-city": {
    "minVersion": "6.1.0"
  },
  "mountain-sun": {
    "minVersion": "6.1.0"
  },
  "mug-hot": {
    "minVersion": "5.6.0"
  },
  "mug-saucer": {
    "minVersion": "3.0.0"
  },
  "music": {
    "minVersion": "1.0.0"
  },
  "n": {
    "minVersion": "6.0.0-beta1"
  },
  "naira-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "network-wired": {
    "minVersion": "5.4.0"
  },
  "neuter": {
    "minVersion": "4.3.0"
  },
  "newspaper": {
    "minVersion": "4.2.0"
  },
  "non-binary": {
    "minVersion": "7.0.0"
  },
  "not-equal": {
    "minVersion": "5.0.13"
  },
  "notdef": {
    "minVersion": "6.0.0-beta1"
  },
  "note-sticky": {
    "minVersion": "4.4.0"
  },
  "notes-medical": {
    "minVersion": "5.0.7"
  },
  "o": {
    "minVersion": "6.0.0-beta1"
  },
  "object-group": {
    "minVersion": "4.4.0"
  },
  "object-ungroup": {
    "minVersion": "4.4.0"
  },
  "octagon": {
    "minVersion": "5.0.0"
  },
  "oil-can": {
    "minVersion": "5.2.0"
  },
  "oil-well": {
    "minVersion": "6.1.0"
  },
  "om": {
    "minVersion": "5.3.0"
  },
  "otter": {
    "minVersion": "5.4.0"
  },
  "outdent": {
    "minVersion": "1.0.0"
  },
  "p": {
    "minVersion": "6.0.0-beta1"
  },
  "pager": {
    "minVersion": "5.7.0"
  },
  "paint-roller": {
    "minVersion": "5.1.0"
  },
  "paintbrush": {
    "minVersion": "4.2.0"
  },
  "palette": {
    "minVersion": "5.0.13"
  },
  "pallet": {
    "minVersion": "5.0.7"
  },
  "panorama": {
    "minVersion": "6.0.0-beta1"
  },
  "paper-plane": {
    "minVersion": "4.1.0"
  },
  "paperclip": {
    "minVersion": "2.0.0"
  },
  "parachute-box": {
    "minVersion": "5.0.9"
  },
  "paragraph": {
    "minVersion": "4.1.0"
  },
  "passport": {
    "minVersion": "5.1.0"
  },
  "paste": {
    "minVersion": "2.0.0"
  },
  "pause": {
    "minVersion": "1.0.0"
  },
  "paw": {
    "minVersion": "4.1.0"
  },
  "peace": {
    "minVersion": "5.3.0"
  },
  "pen": {
    "minVersion": "5.0.0"
  },
  "pen-clip": {
    "minVersion": "5.0.0"
  },
  "pen-fancy": {
    "minVersion": "5.1.0"
  },
  "pen-nib": {
    "minVersion": "5.1.0"
  },
  "pen-ruler": {
    "minVersion": "5.1.0"
  },
  "pen-to-square": {
    "minVersion": "1.0.0"
  },
  "pencil": {
    "minVersion": "1.0.0"
  },
  "pentagon": {
    "minVersion": "7.0.0"
  },
  "people-arrows": {
    "minVersion": "5.13.0"
  },
  "people-carry-box": {
    "minVersion": "5.0.9"
  },
  "people-group": {
    "minVersion": "6.1.0"
  },
  "people-line": {
    "minVersion": "6.1.0"
  },
  "people-pulling": {
    "minVersion": "6.1.0"
  },
  "people-robbery": {
    "minVersion": "6.1.0"
  },
  "people-roof": {
    "minVersion": "6.1.0"
  },
  "pepper-hot": {
    "minVersion": "5.7.0"
  },
  "percent": {
    "minVersion": "4.5.0"
  },
  "person": {
    "minVersion": "3.2.0"
  },
  "person-arrow-down-to-line": {
    "minVersion": "6.1.0"
  },
  "person-arrow-up-from-line": {
    "minVersion": "6.1.0"
  },
  "person-biking": {
    "minVersion": "5.9.0"
  },
  "person-booth": {
    "minVersion": "5.5.0"
  },
  "person-breastfeeding": {
    "minVersion": "6.1.0"
  },
  "person-burst": {
    "minVersion": "6.1.0"
  },
  "person-cane": {
    "minVersion": "6.1.0"
  },
  "person-chalkboard": {
    "minVersion": "6.1.0"
  },
  "person-circle-check": {
    "minVersion": "6.1.0"
  },
  "person-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "person-circle-minus": {
    "minVersion": "6.1.0"
  },
  "person-circle-plus": {
    "minVersion": "6.1.0"
  },
  "person-circle-question": {
    "minVersion": "6.1.0"
  },
  "person-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "person-digging": {
    "minVersion": "5.9.0"
  },
  "person-dots-from-line": {
    "minVersion": "5.0.7"
  },
  "person-dress": {
    "minVersion": "3.2.0"
  },
  "person-dress-burst": {
    "minVersion": "6.1.0"
  },
  "person-drowning": {
    "minVersion": "6.1.0"
  },
  "person-falling": {
    "minVersion": "6.1.0"
  },
  "person-falling-burst": {
    "minVersion": "6.1.0"
  },
  "person-half-dress": {
    "minVersion": "6.1.0"
  },
  "person-harassing": {
    "minVersion": "6.1.0"
  },
  "person-hiking": {
    "minVersion": "5.4.0"
  },
  "person-military-pointing": {
    "minVersion": "6.1.0"
  },
  "person-military-rifle": {
    "minVersion": "6.1.0"
  },
  "person-military-to-person": {
    "minVersion": "6.1.0"
  },
  "person-praying": {
    "minVersion": "5.3.0"
  },
  "person-pregnant": {
    "minVersion": "6.0.0-beta1"
  },
  "person-rays": {
    "minVersion": "6.1.0"
  },
  "person-rifle": {
    "minVersion": "6.1.0"
  },
  "person-running": {
    "minVersion": "5.4.0"
  },
  "person-shelter": {
    "minVersion": "6.1.0"
  },
  "person-skating": {
    "minVersion": "5.6.0"
  },
  "person-skiing": {
    "minVersion": "5.6.0"
  },
  "person-skiing-nordic": {
    "minVersion": "5.6.0"
  },
  "person-snowboarding": {
    "minVersion": "5.6.0"
  },
  "person-swimming": {
    "minVersion": "5.1.0"
  },
  "person-through-window": {
    "minVersion": "6.1.0"
  },
  "person-walking": {
    "minVersion": "5.0.13"
  },
  "person-walking-arrow-loop-left": {
    "minVersion": "6.1.0"
  },
  "person-walking-arrow-right": {
    "minVersion": "6.1.0"
  },
  "person-walking-dashed-line-arrow-right": {
    "minVersion": "6.1.0"
  },
  "person-walking-luggage": {
    "minVersion": "6.1.0"
  },
  "person-walking-with-cane": {
    "minVersion": "4.6.0"
  },
  "peseta-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "peso-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "phone": {
    "minVersion": "2.0.0"
  },
  "phone-flip": {
    "minVersion": "5.9.0"
  },
  "phone-slash": {
    "minVersion": "5.0.0"
  },
  "phone-volume": {
    "minVersion": "4.6.0"
  },
  "photo-film": {
    "minVersion": "5.9.0"
  },
  "picture-in-picture": {
    "minVersion": "7.0.0"
  },
  "piggy-bank": {
    "minVersion": "5.0.9"
  },
  "pills": {
    "minVersion": "5.0.7"
  },
  "pisces": {
    "minVersion": "7.2.0"
  },
  "pizza-slice": {
    "minVersion": "5.7.0"
  },
  "place-of-worship": {
    "minVersion": "5.3.0"
  },
  "plane": {
    "minVersion": "1.0.0"
  },
  "plane-arrival": {
    "minVersion": "5.1.0"
  },
  "plane-circle-check": {
    "minVersion": "6.1.0"
  },
  "plane-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "plane-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "plane-departure": {
    "minVersion": "5.1.0"
  },
  "plane-lock": {
    "minVersion": "6.1.0"
  },
  "plane-slash": {
    "minVersion": "5.13.0"
  },
  "plane-up": {
    "minVersion": "6.0.0-beta1"
  },
  "plant-wilt": {
    "minVersion": "6.1.0"
  },
  "plate-wheat": {
    "minVersion": "6.1.0"
  },
  "play": {
    "minVersion": "1.0.0"
  },
  "plug": {
    "minVersion": "4.2.0"
  },
  "plug-circle-bolt": {
    "minVersion": "6.1.0"
  },
  "plug-circle-check": {
    "minVersion": "6.1.0"
  },
  "plug-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "plug-circle-minus": {
    "minVersion": "6.1.0"
  },
  "plug-circle-plus": {
    "minVersion": "6.1.0"
  },
  "plug-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "plus": {
    "minVersion": "1.0.0"
  },
  "plus-minus": {
    "minVersion": "6.0.0-beta1"
  },
  "podcast": {
    "minVersion": "4.7.0"
  },
  "poo": {
    "minVersion": "5.0.0"
  },
  "poo-storm": {
    "minVersion": "5.5.0"
  },
  "poop": {
    "minVersion": "5.2.0"
  },
  "power-off": {
    "minVersion": "1.0.0"
  },
  "prescription": {
    "minVersion": "5.1.0"
  },
  "prescription-bottle": {
    "minVersion": "5.0.7"
  },
  "prescription-bottle-medical": {
    "minVersion": "5.0.7"
  },
  "print": {
    "minVersion": "1.0.0"
  },
  "pump-medical": {
    "minVersion": "5.13.0"
  },
  "pump-soap": {
    "minVersion": "5.13.0"
  },
  "puzzle-piece": {
    "minVersion": "3.1.0"
  },
  "q": {
    "minVersion": "6.0.0-beta1"
  },
  "qrcode": {
    "minVersion": "1.0.0"
  },
  "question": {
    "minVersion": "3.1.0"
  },
  "quote-left": {
    "minVersion": "3.0.0"
  },
  "quote-right": {
    "minVersion": "3.0.0"
  },
  "r": {
    "minVersion": "6.0.0-beta1"
  },
  "radiation": {
    "minVersion": "5.6.0"
  },
  "radio": {
    "minVersion": "5.11.0"
  },
  "rainbow": {
    "minVersion": "5.5.0"
  },
  "ranking-star": {
    "minVersion": "6.1.0"
  },
  "receipt": {
    "minVersion": "5.0.13"
  },
  "record-vinyl": {
    "minVersion": "5.11.0"
  },
  "rectangle-ad": {
    "minVersion": "5.3.0"
  },
  "rectangle-list": {
    "minVersion": "1.0.0"
  },
  "rectangle-xmark": {
    "minVersion": "4.7.0"
  },
  "recycle": {
    "minVersion": "4.1.0"
  },
  "registered": {
    "minVersion": "4.4.0"
  },
  "repeat": {
    "minVersion": "5.0.0"
  },
  "reply": {
    "minVersion": "3.0.0"
  },
  "reply-all": {
    "minVersion": "3.1.0"
  },
  "republican": {
    "minVersion": "5.5.0"
  },
  "restroom": {
    "minVersion": "5.6.0"
  },
  "retweet": {
    "minVersion": "1.0.0"
  },
  "ribbon": {
    "minVersion": "5.0.9"
  },
  "right-from-bracket": {
    "minVersion": "5.0.0"
  },
  "right-left": {
    "minVersion": "5.0.0"
  },
  "right-long": {
    "minVersion": "5.0.0"
  },
  "right-to-bracket": {
    "minVersion": "5.0.0"
  },
  "ring": {
    "minVersion": "5.4.0"
  },
  "road": {
    "minVersion": "1.0.0"
  },
  "road-barrier": {
    "minVersion": "6.1.0"
  },
  "road-bridge": {
    "minVersion": "6.1.0"
  },
  "road-circle-check": {
    "minVersion": "6.1.0"
  },
  "road-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "road-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "road-lock": {
    "minVersion": "6.1.0"
  },
  "road-spikes": {
    "minVersion": "6.1.0"
  },
  "robot": {
    "minVersion": "5.0.13"
  },
  "rocket": {
    "minVersion": "3.1.0"
  },
  "rotate": {
    "minVersion": "5.0.0"
  },
  "rotate-left": {
    "minVersion": "5.0.0"
  },
  "rotate-right": {
    "minVersion": "5.0.0"
  },
  "route": {
    "minVersion": "5.0.9"
  },
  "rss": {
    "minVersion": "2.0.0"
  },
  "ruble-sign": {
    "minVersion": "4.0.0"
  },
  "rug": {
    "minVersion": "6.1.0"
  },
  "ruler": {
    "minVersion": "5.0.13"
  },
  "ruler-combined": {
    "minVersion": "5.0.13"
  },
  "ruler-horizontal": {
    "minVersion": "5.0.13"
  },
  "ruler-vertical": {
    "minVersion": "5.0.13"
  },
  "rupee-sign": {
    "minVersion": "3.2.0"
  },
  "rupiah-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "s": {
    "minVersion": "6.0.0-beta1"
  },
  "sack-dollar": {
    "minVersion": "5.7.0"
  },
  "sack-xmark": {
    "minVersion": "6.1.0"
  },
  "sagittarius": {
    "minVersion": "7.2.0"
  },
  "sailboat": {
    "minVersion": "6.0.0-beta2"
  },
  "satellite": {
    "minVersion": "5.6.0"
  },
  "satellite-dish": {
    "minVersion": "5.6.0"
  },
  "scale-balanced": {
    "minVersion": "4.4.0"
  },
  "scale-unbalanced": {
    "minVersion": "5.0.13"
  },
  "scale-unbalanced-flip": {
    "minVersion": "5.0.13"
  },
  "school": {
    "minVersion": "5.0.13"
  },
  "school-circle-check": {
    "minVersion": "6.1.0"
  },
  "school-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "school-circle-xmark": {
    "minVersion": "6.1.0"
  },
  "school-flag": {
    "minVersion": "6.1.0"
  },
  "school-lock": {
    "minVersion": "6.1.0"
  },
  "scissors": {
    "minVersion": "2.0.0"
  },
  "scorpio": {
    "minVersion": "7.2.0"
  },
  "screwdriver": {
    "minVersion": "5.0.13"
  },
  "screwdriver-wrench": {
    "minVersion": "5.6.0"
  },
  "scroll": {
    "minVersion": "5.4.0"
  },
  "scroll-torah": {
    "minVersion": "5.3.0"
  },
  "sd-card": {
    "minVersion": "5.6.0"
  },
  "section": {
    "minVersion": "6.0.0-beta1"
  },
  "seedling": {
    "minVersion": "5.0.9"
  },
  "septagon": {
    "minVersion": "7.0.0"
  },
  "server": {
    "minVersion": "4.3.0"
  },
  "shapes": {
    "minVersion": "5.2.0"
  },
  "share": {
    "minVersion": "1.0.0"
  },
  "share-from-square": {
    "minVersion": "3.1.0"
  },
  "share-nodes": {
    "minVersion": "4.1.0"
  },
  "sheet-plastic": {
    "minVersion": "6.1.0"
  },
  "shekel-sign": {
    "minVersion": "4.2.0"
  },
  "shield": {
    "minVersion": "3.1.0"
  },
  "shield-cat": {
    "minVersion": "6.1.0"
  },
  "shield-dog": {
    "minVersion": "6.1.0"
  },
  "shield-halved": {
    "minVersion": "5.0.0"
  },
  "shield-heart": {
    "minVersion": "6.1.0"
  },
  "shield-virus": {
    "minVersion": "5.13.0"
  },
  "ship": {
    "minVersion": "4.3.0"
  },
  "shirt": {
    "minVersion": "5.0.13"
  },
  "shoe-prints": {
    "minVersion": "5.0.13"
  },
  "shop": {
    "minVersion": "5.0.13"
  },
  "shop-lock": {
    "minVersion": "6.0.0"
  },
  "shop-slash": {
    "minVersion": "5.13.0"
  },
  "shower": {
    "minVersion": "4.7.0"
  },
  "shrimp": {
    "minVersion": "6.0.0-beta2"
  },
  "shuffle": {
    "minVersion": "1.0.0"
  },
  "shuttle-space": {
    "minVersion": "4.1.0"
  },
  "sign-hanging": {
    "minVersion": "5.0.9"
  },
  "signal": {
    "minVersion": "1.0.0"
  },
  "signature": {
    "minVersion": "5.1.0"
  },
  "signs-post": {
    "minVersion": "4.4.0"
  },
  "sim-card": {
    "minVersion": "5.6.0"
  },
  "single-quote-left": {
    "minVersion": "7.0.0"
  },
  "single-quote-right": {
    "minVersion": "7.0.0"
  },
  "sink": {
    "minVersion": "5.13.0"
  },
  "sitemap": {
    "minVersion": "2.0.0"
  },
  "skull": {
    "minVersion": "5.0.13"
  },
  "skull-crossbones": {
    "minVersion": "5.4.0"
  },
  "slash": {
    "minVersion": "5.4.0"
  },
  "sleigh": {
    "minVersion": "5.6.0"
  },
  "sliders": {
    "minVersion": "4.1.0"
  },
  "smog": {
    "minVersion": "5.5.0"
  },
  "smoking": {
    "minVersion": "5.0.7"
  },
  "snowflake": {
    "minVersion": "4.7.0"
  },
  "snowman": {
    "minVersion": "5.6.0"
  },
  "snowplow": {
    "minVersion": "5.6.0"
  },
  "soap": {
    "minVersion": "5.13.0"
  },
  "socks": {
    "minVersion": "5.3.0"
  },
  "solar-panel": {
    "minVersion": "5.1.0"
  },
  "sort": {
    "minVersion": "2.0.0"
  },
  "sort-down": {
    "minVersion": "2.0.0"
  },
  "sort-up": {
    "minVersion": "2.0.0"
  },
  "spa": {
    "minVersion": "5.1.0"
  },
  "spaghetti-monster-flying": {
    "minVersion": "5.3.0"
  },
  "spell-check": {
    "minVersion": "5.9.0"
  },
  "spider": {
    "minVersion": "5.4.0"
  },
  "spinner": {
    "minVersion": "3.0.0"
  },
  "spiral": {
    "minVersion": "7.0.0"
  },
  "splotch": {
    "minVersion": "5.1.0"
  },
  "spoon": {
    "minVersion": "5.0.0"
  },
  "spray-can": {
    "minVersion": "5.1.0"
  },
  "spray-can-sparkles": {
    "minVersion": "5.2.0"
  },
  "square": {
    "minVersion": "2.0.0"
  },
  "square-arrow-up-right": {
    "minVersion": "3.1.0"
  },
  "square-binary": {
    "minVersion": "6.7.0"
  },
  "square-caret-down": {
    "minVersion": "3.2.0"
  },
  "square-caret-left": {
    "minVersion": "4.0.0"
  },
  "square-caret-right": {
    "minVersion": "3.2.0"
  },
  "square-caret-up": {
    "minVersion": "3.2.0"
  },
  "square-check": {
    "minVersion": "3.1.0"
  },
  "square-envelope": {
    "minVersion": "4.1.0"
  },
  "square-full": {
    "minVersion": "5.0.5"
  },
  "square-h": {
    "minVersion": "3.0.0"
  },
  "square-minus": {
    "minVersion": "3.1.0"
  },
  "square-nfi": {
    "minVersion": "6.1.0"
  },
  "square-parking": {
    "minVersion": "5.0.13"
  },
  "square-pen": {
    "minVersion": "3.1.0"
  },
  "square-person-confined": {
    "minVersion": "6.1.0"
  },
  "square-phone": {
    "minVersion": "2.0.0"
  },
  "square-phone-flip": {
    "minVersion": "5.9.0"
  },
  "square-plus": {
    "minVersion": "3.0.0"
  },
  "square-poll-horizontal": {
    "minVersion": "5.3.0"
  },
  "square-poll-vertical": {
    "minVersion": "5.3.0"
  },
  "square-root-variable": {
    "minVersion": "5.3.0"
  },
  "square-rss": {
    "minVersion": "3.1.0"
  },
  "square-share-nodes": {
    "minVersion": "4.1.0"
  },
  "square-up-right": {
    "minVersion": "5.0.0"
  },
  "square-virus": {
    "minVersion": "6.1.0"
  },
  "square-xmark": {
    "minVersion": "4.7.0"
  },
  "staff-snake": {
    "minVersion": "6.1.0"
  },
  "stairs": {
    "minVersion": "6.0.0-beta1"
  },
  "stamp": {
    "minVersion": "5.1.0"
  },
  "stapler": {
    "minVersion": "6.1.2"
  },
  "star": {
    "minVersion": "1.0.0"
  },
  "star-and-crescent": {
    "minVersion": "5.3.0"
  },
  "star-half": {
    "minVersion": "1.0.0"
  },
  "star-half-stroke": {
    "minVersion": "5.1.0"
  },
  "star-of-david": {
    "minVersion": "5.3.0"
  },
  "star-of-life": {
    "minVersion": "5.2.0"
  },
  "sterling-sign": {
    "minVersion": "3.2.0"
  },
  "stethoscope": {
    "minVersion": "3.0.0"
  },
  "stop": {
    "minVersion": "1.0.0"
  },
  "stopwatch": {
    "minVersion": "5.0.0"
  },
  "stopwatch-20": {
    "minVersion": "5.13.0"
  },
  "store": {
    "minVersion": "5.0.13"
  },
  "store-slash": {
    "minVersion": "5.13.0"
  },
  "street-view": {
    "minVersion": "4.3.0"
  },
  "strikethrough": {
    "minVersion": "2.0.0"
  },
  "stroopwafel": {
    "minVersion": "5.0.13"
  },
  "subscript": {
    "minVersion": "3.1.0"
  },
  "suitcase": {
    "minVersion": "3.0.0"
  },
  "suitcase-medical": {
    "minVersion": "3.0.0"
  },
  "suitcase-rolling": {
    "minVersion": "5.1.0"
  },
  "sun": {
    "minVersion": "3.2.0"
  },
  "sun-plant-wilt": {
    "minVersion": "6.1.0"
  },
  "superscript": {
    "minVersion": "3.1.0"
  },
  "swatchbook": {
    "minVersion": "5.1.0"
  },
  "synagogue": {
    "minVersion": "5.3.0"
  },
  "syringe": {
    "minVersion": "5.0.7"
  },
  "t": {
    "minVersion": "6.0.0-beta1"
  },
  "table": {
    "minVersion": "2.0.0"
  },
  "table-cells": {
    "minVersion": "1.0.0"
  },
  "table-cells-column-lock": {
    "minVersion": "6.5.2"
  },
  "table-cells-large": {
    "minVersion": "1.0.0"
  },
  "table-cells-row-lock": {
    "minVersion": "6.5.2"
  },
  "table-cells-row-unlock": {
    "minVersion": "6.6.0"
  },
  "table-columns": {
    "minVersion": "2.0.0"
  },
  "table-list": {
    "minVersion": "1.0.0"
  },
  "table-tennis-paddle-ball": {
    "minVersion": "5.0.5"
  },
  "tablet": {
    "minVersion": "5.0.0"
  },
  "tablet-button": {
    "minVersion": "3.0.0"
  },
  "tablet-screen-button": {
    "minVersion": "5.0.0"
  },
  "tablets": {
    "minVersion": "5.0.7"
  },
  "tachograph-digital": {
    "minVersion": "5.1.0"
  },
  "tag": {
    "minVersion": "1.0.0"
  },
  "tags": {
    "minVersion": "1.0.0"
  },
  "tape": {
    "minVersion": "5.0.9"
  },
  "tarp": {
    "minVersion": "6.1.0"
  },
  "tarp-droplet": {
    "minVersion": "6.1.0"
  },
  "taurus": {
    "minVersion": "7.2.0"
  },
  "taxi": {
    "minVersion": "4.1.0"
  },
  "teeth": {
    "minVersion": "5.2.0"
  },
  "teeth-open": {
    "minVersion": "5.2.0"
  },
  "temperature-arrow-down": {
    "minVersion": "5.12.0"
  },
  "temperature-arrow-up": {
    "minVersion": "5.12.0"
  },
  "temperature-empty": {
    "minVersion": "4.7.0"
  },
  "temperature-full": {
    "minVersion": "4.7.0"
  },
  "temperature-half": {
    "minVersion": "4.7.0"
  },
  "temperature-high": {
    "minVersion": "5.5.0"
  },
  "temperature-low": {
    "minVersion": "5.5.0"
  },
  "temperature-quarter": {
    "minVersion": "4.7.0"
  },
  "temperature-three-quarters": {
    "minVersion": "4.7.0"
  },
  "tenge-sign": {
    "minVersion": "5.6.0"
  },
  "tent": {
    "minVersion": "6.1.0"
  },
  "tent-arrow-down-to-line": {
    "minVersion": "6.1.0"
  },
  "tent-arrow-left-right": {
    "minVersion": "6.1.0"
  },
  "tent-arrow-turn-left": {
    "minVersion": "6.1.0"
  },
  "tent-arrows-down": {
    "minVersion": "6.1.0"
  },
  "tents": {
    "minVersion": "6.1.0"
  },
  "terminal": {
    "minVersion": "3.1.0"
  },
  "text-height": {
    "minVersion": "1.0.0"
  },
  "text-slash": {
    "minVersion": "5.9.0"
  },
  "text-width": {
    "minVersion": "1.0.0"
  },
  "thermometer": {
    "minVersion": "5.0.7"
  },
  "thumbs-down": {
    "minVersion": "3.2.0"
  },
  "thumbs-up": {
    "minVersion": "3.2.0"
  },
  "thumbtack": {
    "minVersion": "1.0.0"
  },
  "thumbtack-slash": {
    "minVersion": "6.6.0"
  },
  "ticket": {
    "minVersion": "3.1.0"
  },
  "ticket-simple": {
    "minVersion": "5.0.0"
  },
  "timeline": {
    "minVersion": "6.0.0-beta1"
  },
  "toggle-off": {
    "minVersion": "4.2.0"
  },
  "toggle-on": {
    "minVersion": "4.2.0"
  },
  "toilet": {
    "minVersion": "5.6.0"
  },
  "toilet-paper": {
    "minVersion": "5.4.0"
  },
  "toilet-paper-slash": {
    "minVersion": "5.13.0"
  },
  "toilet-portable": {
    "minVersion": "6.1.0"
  },
  "toilets-portable": {
    "minVersion": "6.1.0"
  },
  "toolbox": {
    "minVersion": "5.0.13"
  },
  "tooth": {
    "minVersion": "5.1.0"
  },
  "torii-gate": {
    "minVersion": "5.3.0"
  },
  "tornado": {
    "minVersion": "5.5.0"
  },
  "tower-broadcast": {
    "minVersion": "5.0.13"
  },
  "tower-cell": {
    "minVersion": "6.1.0"
  },
  "tower-observation": {
    "minVersion": "6.1.0"
  },
  "tractor": {
    "minVersion": "5.4.0"
  },
  "trademark": {
    "minVersion": "4.4.0"
  },
  "traffic-light": {
    "minVersion": "5.2.0"
  },
  "trailer": {
    "minVersion": "5.12.0"
  },
  "train": {
    "minVersion": "4.3.0"
  },
  "train-subway": {
    "minVersion": "4.3.0"
  },
  "train-tram": {
    "minVersion": "5.6.0"
  },
  "transgender": {
    "minVersion": "4.3.0"
  },
  "trash": {
    "minVersion": "4.2.0"
  },
  "trash-arrow-up": {
    "minVersion": "5.7.0"
  },
  "trash-can": {
    "minVersion": "5.0.0"
  },
  "trash-can-arrow-up": {
    "minVersion": "5.7.0"
  },
  "tree": {
    "minVersion": "4.1.0"
  },
  "tree-city": {
    "minVersion": "6.1.0"
  },
  "triangle-exclamation": {
    "minVersion": "1.0.0"
  },
  "trophy": {
    "minVersion": "1.0.0"
  },
  "trowel": {
    "minVersion": "6.1.0"
  },
  "trowel-bricks": {
    "minVersion": "6.1.0"
  },
  "truck": {
    "minVersion": "2.0.0"
  },
  "truck-arrow-right": {
    "minVersion": "6.1.0"
  },
  "truck-droplet": {
    "minVersion": "6.1.0"
  },
  "truck-fast": {
    "minVersion": "5.0.7"
  },
  "truck-field": {
    "minVersion": "6.1.0"
  },
  "truck-field-un": {
    "minVersion": "6.1.0"
  },
  "truck-front": {
    "minVersion": "6.0.0-beta1"
  },
  "truck-medical": {
    "minVersion": "3.0.0"
  },
  "truck-monster": {
    "minVersion": "5.2.0"
  },
  "truck-moving": {
    "minVersion": "5.0.9"
  },
  "truck-pickup": {
    "minVersion": "5.2.0"
  },
  "truck-plane": {
    "minVersion": "6.1.0"
  },
  "truck-ramp-box": {
    "minVersion": "5.0.9"
  },
  "tty": {
    "minVersion": "4.2.0"
  },
  "turkish-lira-sign": {
    "minVersion": "6.0.0-beta1"
  },
  "turn-down": {
    "minVersion": "5.0.0"
  },
  "turn-up": {
    "minVersion": "5.0.0"
  },
  "tv": {
    "minVersion": "4.4.0"
  },
  "u": {
    "minVersion": "6.0.0-beta1"
  },
  "umbrella": {
    "minVersion": "2.0.0"
  },
  "umbrella-beach": {
    "minVersion": "5.1.0"
  },
  "underline": {
    "minVersion": "2.0.0"
  },
  "universal-access": {
    "minVersion": "4.6.0"
  },
  "unlock": {
    "minVersion": "2.0.0"
  },
  "unlock-keyhole": {
    "minVersion": "3.1.0"
  },
  "up-down": {
    "minVersion": "5.0.0"
  },
  "up-down-left-right": {
    "minVersion": "2.0.0"
  },
  "up-long": {
    "minVersion": "5.0.0"
  },
  "up-right-and-down-left-from-center": {
    "minVersion": "1.0.0"
  },
  "up-right-from-square": {
    "minVersion": "5.0.0"
  },
  "upload": {
    "minVersion": "1.0.0"
  },
  "user": {
    "minVersion": "1.0.0"
  },
  "user-astronaut": {
    "minVersion": "5.0.11"
  },
  "user-check": {
    "minVersion": "5.0.11"
  },
  "user-clock": {
    "minVersion": "5.0.11"
  },
  "user-doctor": {
    "minVersion": "2.0.0"
  },
  "user-gear": {
    "minVersion": "5.0.11"
  },
  "user-graduate": {
    "minVersion": "5.0.11"
  },
  "user-group": {
    "minVersion": "5.0.11"
  },
  "user-injured": {
    "minVersion": "5.4.0"
  },
  "user-lock": {
    "minVersion": "5.0.11"
  },
  "user-minus": {
    "minVersion": "5.0.11"
  },
  "user-ninja": {
    "minVersion": "5.0.11"
  },
  "user-nurse": {
    "minVersion": "5.7.0"
  },
  "user-pen": {
    "minVersion": "5.0.11"
  },
  "user-plus": {
    "minVersion": "4.3.0"
  },
  "user-secret": {
    "minVersion": "4.3.0"
  },
  "user-shield": {
    "minVersion": "5.0.11"
  },
  "user-slash": {
    "minVersion": "5.0.11"
  },
  "user-tag": {
    "minVersion": "5.0.11"
  },
  "user-tie": {
    "minVersion": "5.0.11"
  },
  "user-xmark": {
    "minVersion": "4.3.0"
  },
  "users": {
    "minVersion": "2.0.0"
  },
  "users-between-lines": {
    "minVersion": "6.1.0"
  },
  "users-gear": {
    "minVersion": "5.0.11"
  },
  "users-line": {
    "minVersion": "6.1.0"
  },
  "users-rays": {
    "minVersion": "6.1.0"
  },
  "users-rectangle": {
    "minVersion": "6.1.0"
  },
  "users-slash": {
    "minVersion": "5.13.0"
  },
  "users-viewfinder": {
    "minVersion": "6.1.0"
  },
  "utensils": {
    "minVersion": "5.0.0"
  },
  "v": {
    "minVersion": "6.0.0-beta1"
  },
  "van-shuttle": {
    "minVersion": "5.1.0"
  },
  "vault": {
    "minVersion": "6.0.0-beta1"
  },
  "venus": {
    "minVersion": "4.3.0"
  },
  "venus-double": {
    "minVersion": "4.3.0"
  },
  "venus-mars": {
    "minVersion": "4.3.0"
  },
  "vest": {
    "minVersion": "5.15.0"
  },
  "vest-patches": {
    "minVersion": "5.15.0"
  },
  "vial": {
    "minVersion": "5.0.7"
  },
  "vial-circle-check": {
    "minVersion": "6.1.0"
  },
  "vial-virus": {
    "minVersion": "6.1.0"
  },
  "vials": {
    "minVersion": "5.0.7"
  },
  "video": {
    "minVersion": "1.0.0"
  },
  "video-slash": {
    "minVersion": "5.0.9"
  },
  "vihara": {
    "minVersion": "5.3.0"
  },
  "virgo": {
    "minVersion": "7.2.0"
  },
  "virus": {
    "minVersion": "5.13.0"
  },
  "virus-covid": {
    "minVersion": "6.0.0"
  },
  "virus-covid-slash": {
    "minVersion": "6.0.0"
  },
  "virus-slash": {
    "minVersion": "5.13.0"
  },
  "viruses": {
    "minVersion": "5.13.0"
  },
  "voicemail": {
    "minVersion": "5.9.0"
  },
  "volcano": {
    "minVersion": "5.5.0"
  },
  "volleyball": {
    "minVersion": "5.0.5"
  },
  "volume": {
    "minVersion": "5.3.0"
  },
  "volume-high": {
    "minVersion": "1.0.0"
  },
  "volume-low": {
    "minVersion": "1.0.0"
  },
  "volume-off": {
    "minVersion": "1.0.0"
  },
  "volume-xmark": {
    "minVersion": "5.3.0"
  },
  "vr-cardboard": {
    "minVersion": "5.4.0"
  },
  "w": {
    "minVersion": "6.0.0-beta1"
  },
  "walkie-talkie": {
    "minVersion": "5.11.0"
  },
  "wallet": {
    "minVersion": "5.0.13"
  },
  "wand-magic": {
    "minVersion": "2.0.0"
  },
  "wand-magic-sparkles": {
    "minVersion": "6.0.0-beta1"
  },
  "wand-sparkles": {
    "minVersion": "5.4.0"
  },
  "warehouse": {
    "minVersion": "5.0.7"
  },
  "water": {
    "minVersion": "5.5.0"
  },
  "water-ladder": {
    "minVersion": "5.1.0"
  },
  "wave-square": {
    "minVersion": "5.8.0"
  },
  "web-awesome": {
    "minVersion": "6.5.2"
  },
  "weight-hanging": {
    "minVersion": "5.1.0"
  },
  "weight-scale": {
    "minVersion": "5.0.7"
  },
  "wheat-awn": {
    "minVersion": "6.0.0-beta1"
  },
  "wheat-awn-circle-exclamation": {
    "minVersion": "6.1.0"
  },
  "wheelchair": {
    "minVersion": "4.0.0"
  },
  "wheelchair-move": {
    "minVersion": "6.0.0-beta1"
  },
  "whiskey-glass": {
    "minVersion": "5.6.0"
  },
  "wifi": {
    "minVersion": "4.2.0"
  },
  "wind": {
    "minVersion": "5.4.0"
  },
  "window-maximize": {
    "minVersion": "4.7.0"
  },
  "window-minimize": {
    "minVersion": "4.7.0"
  },
  "window-restore": {
    "minVersion": "4.7.0"
  },
  "wine-bottle": {
    "minVersion": "5.4.0"
  },
  "wine-glass": {
    "minVersion": "5.0.9"
  },
  "wine-glass-empty": {
    "minVersion": "5.1.0"
  },
  "won-sign": {
    "minVersion": "3.2.0"
  },
  "worm": {
    "minVersion": "6.1.0"
  },
  "wrench": {
    "minVersion": "2.0.0"
  },
  "x": {
    "minVersion": "6.0.0-beta1"
  },
  "x-ray": {
    "minVersion": "5.0.7"
  },
  "xmark": {
    "minVersion": "1.0.0"
  },
  "xmarks-lines": {
    "minVersion": "6.1.0"
  },
  "y": {
    "minVersion": "6.0.0-beta1"
  },
  "yen-sign": {
    "minVersion": "3.2.0"
  },
  "yin-yang": {
    "minVersion": "5.3.0"
  },
  "z": {
    "minVersion": "6.0.0-beta1"
  }
} as const

export default solidIcons
